QBShared = QBShared or {}
QBShared.VehicleHashes = {}

QBShared.Vehicles = {
	--- Compacts
	['asbo'] = {
		['name'] = 'Asbo',
		['brand'] = 'Maxwell',
		['model'] = 'asbo',
		['price'] = 4000,
		['category'] = 'compacts',
		['hash'] = `asbo`,
		['shop'] = 'pdm',
	},
	['blista'] = {
		['name'] = 'Blista',
		['brand'] = 'Dinka',
		['model'] = 'blista',
		['price'] = 13000,
		['category'] = 'compacts',
		['hash'] = `blista`,
		['shop'] = 'pdm',
	},
	['brioso'] = {
		['name'] = 'Brioso R/A',
		['brand'] = 'Grotti',
		['model'] = 'brioso',
		['price'] = 20000,
		['category'] = 'compacts',
		['hash'] = `brioso`,
		['shop'] = 'pdm',
	},
	['club'] = {
		['name'] = 'Club',
		['brand'] = 'BF',
		['model'] = 'club',
		['price'] = 8000,
		['category'] = 'compacts',
		['hash'] = `club`,
		['shop'] = 'pdm',
	},
	['dilettante'] = {
		['name'] = 'Dilettante',
		['brand'] = 'Karin',
		['model'] = 'dilettante',
		['price'] = 9000,
		['category'] = 'compacts',
		['hash'] = `dilettante`,
		['shop'] = 'pdm',
	},
	['kanjo'] = {
		['name'] = 'Blista Kanjo',
		['brand'] = 'Dinka',
		['model'] = 'kanjo',
		['price'] = 12000,
		['category'] = 'compacts',
		['hash'] = `kanjo`,
		['shop'] = 'pdm',
	},
	['issi2'] = {
		['name'] = 'Issi',
		['brand'] = 'Weeny',
		['model'] = 'issi2',
		['price'] = 7000,
		['category'] = 'compacts',
		['hash'] = `issi2`,
		['shop'] = 'pdm',
	},
	['issi3'] = {
		['name'] = 'Issi Classic',
		['brand'] = 'Weeny',
		['model'] = 'issi3',
		['price'] = 5000,
		['category'] = 'compacts',
		['hash'] = `issi3`,
		['shop'] = 'pdm',
	},
	['panto'] = {
		['name'] = 'Panto',
		['brand'] = 'Benefactor',
		['model'] = 'panto',
		['price'] = 3200,
		['category'] = 'compacts',
		['hash'] = `panto`,
		['shop'] = 'pdm',
	},
	['prairie'] = {
		['name'] = 'Prairie',
		['brand'] = 'Bollokan',
		['model'] = 'prairie',
		['price'] = 30000,
		['category'] = 'compacts',
		['hash'] = `prairie`,
		['shop'] = 'pdm',
	},
	['rhapsody'] = {
		['name'] = 'Rhapsody',
		['brand'] = 'Declasse',
		['model'] = 'rhapsody',
		['price'] = 10000,
		['category'] = 'compacts',
		['hash'] = `rhapsody`,
		['shop'] = 'pdm',
	},
	['brioso2'] = {
		['name'] = 'Brioso 300',
		['brand'] = 'Grotti',
		['model'] = 'brioso2',
		['price'] = 12000,
		['category'] = 'compacts',
		['hash'] = `brioso2`,
		['shop'] = 'pdm',
	},
	['weevil'] = {
		['name'] = 'Weevil',
		['brand'] = 'BF',
		['model'] = 'weevil',
		['price'] = 9000,
		['category'] = 'compacts',
		['hash'] = `weevil`,
		['shop'] = 'pdm',
	},
	--- Coupes
	['cogcabrio'] = {
		['name'] = 'Cognoscenti Cabrio',
		['brand'] = 'Enus',
		['model'] = 'cogcabrio',
		['price'] = 30000,
		['category'] = 'coupes',
		['hash'] = `cogcabrio`,
		['shop'] = 'pdm',
	},
	['exemplar'] = {
		['name'] = 'Exemplar',
		['brand'] = 'Dewbauchee',
		['model'] = 'exemplar',
		['price'] = 40000,
		['category'] = 'coupes',
		['hash'] = `exemplar`,
		['shop'] = 'pdm',
	},
	['f620'] = {
		['name'] = 'F620',
		['brand'] = 'Ocelot',
		['model'] = 'f620',
		['price'] = 32500,
		['category'] = 'coupes',
		['hash'] = `f620`,
		['shop'] = 'pdm',
	},
	['felon'] = {
		['name'] = 'Felon',
		['brand'] = 'Lampadati',
		['model'] = 'felon',
		['price'] = 31000,
		['category'] = 'coupes',
		['hash'] = `felon`,
		['shop'] = 'pdm',
	},
	['felon2'] = {
		['name'] = 'Felon GT',
		['brand'] = 'Lampadati',
		['model'] = 'felon2',
		['price'] = 37000,
		['category'] = 'coupes',
		['hash'] = `felon2`,
		['shop'] = 'pdm',
	},
	['jackal'] = {
		['name'] = 'Jackal',
		['brand'] = 'Ocelot',
		['model'] = 'jackal',
		['price'] = 19000,
		['category'] = 'coupes',
		['hash'] = `jackal`,
		['shop'] = 'pdm',
	},
	['oracle'] = {
		['name'] = 'Oracle',
		['brand'] = 'Ubermacht',
		['model'] = 'oracle',
		['price'] = 22000,
		['category'] = 'sedans',
		['hash'] = `oracle`,
		['shop'] = 'pdm',
	},
	['oracle2'] = {
		['name'] = 'Oracle XS',
		['brand'] = 'Übermacht',
		['model'] = 'oracle2',
		['price'] = 28000,
		['category'] = 'coupes',
		['hash'] = `oracle2`,
		['shop'] = 'pdm',
	},
	['sentinel'] = {
		['name'] = 'Sentinel',
		['brand'] = 'Übermacht',
		['model'] = 'sentinel',
		['price'] = 30000,
		['category'] = 'coupes',
		['hash'] = `sentinel`,
		['shop'] = 'pdm',
	},
	['sentinel2'] = {
		['name'] = 'Sentinel XS',
		['brand'] = ' Übermacht',
		['model'] = 'sentinel2',
		['price'] = 33000,
		['category'] = 'coupes',
		['hash'] = `sentinel2`,
		['shop'] = 'pdm',
	},
	['windsor'] = {
		['name'] = 'Windsor',
		['brand'] = 'Enus',
		['model'] = 'windsor',
		['price'] = 27000,
		['category'] = 'coupes',
		['hash'] = `windsor`,
		['shop'] = 'pdm',
	},
	['windsor2'] = {
		['name'] = 'Windsor Drop',
		['brand'] = 'Enus',
		['model'] = 'windsor2',
		['price'] = 34000,
		['category'] = 'coupes',
		['hash'] = `windsor2`,
		['shop'] = 'pdm',
	},
	['zion'] = {
		['name'] = 'Zion',
		['brand'] = 'Übermacht',
		['model'] = 'zion',
		['price'] = 22000,
		['category'] = 'coupes',
		['hash'] = `zion`,
		['shop'] = 'pdm',
	},
	['zion2'] = {
		['name'] = 'Zion Cabrio',
		['brand'] = 'Übermacht',
		['model'] = 'zion2',
		['price'] = 28000,
		['category'] = 'coupes',
		['hash'] = `zion2`,
		['shop'] = 'pdm',
	},
	['previon'] = {			--DLC +set sv_enforceGameBuild 2372
		['name'] = 'Previon',
		['brand'] = 'Karin',
		['model'] = 'previon',
		['price'] = 149000,
		['category'] = 'coupes',
		['hash'] = `previon`,
		['shop'] = 'pdm',
	},
	['ignus'] = { 	 	--DLC +set sv_enforceGameBuild 2545
		['name'] = 'Ignus',
		['brand'] = 'Pegassi',
		['model'] = 'ignus',
		['price'] = 1120000,
		['category'] = 'coupes',
		['hash'] = `ignus`,
		['shop'] = 'pdm',
	},
	--- Cycles
	['bmx'] = {
		['name'] = 'BMX',
        ['brand'] = 'Bike',
		['model'] = 'bmx',
		['price'] = 160,
		['category'] = 'cycles',
		['hash'] = `bmx`,
		['shop'] = 'pdm',
	},
	['cruiser'] = {
		['name'] = 'Cruiser',
        ['brand'] = 'Bike',
		['model'] = 'cruiser',
		['price'] = 510,
		['category'] = 'cycles',
		['hash'] = `cruiser`,
		['shop'] = 'pdm',
	},
	['fixter'] = {
		['name'] = 'Fixter',
        ['brand'] = 'Bike',
		['model'] = 'fixter',
		['price'] = 225,
		['category'] = 'cycles',
		['hash'] = `fixter`,
		['shop'] = 'pdm',
	},
	['scorcher'] = {
		['name'] = 'Scorcher',
        ['brand'] = 'Bike',
		['model'] = 'scorcher',
		['price'] = 280,
		['category'] = 'cycles',
		['hash'] = `scorcher`,
		['shop'] = 'pdm',
	},
	['tribike'] = {
		['name'] = 'Tri Bike',
        ['brand'] = 'Bike',
		['model'] = 'tribike',
		['price'] = 500,
		['category'] = 'cycles',
		['hash'] = `tribike`,
		['shop'] = 'pdm',
	},
	['tribike2'] = {
		['name'] = 'Tri Bike 2',
        ['brand'] = 'Bike',
		['model'] = 'tribike2',
		['price'] = 700,
		['category'] = 'cycles',
		['hash'] = `tribike2`,
		['shop'] = 'pdm',
	},
	['tribike3'] = {
		['name'] = 'Tri Bike 3',
        ['brand'] = 'Bike',
		['model'] = 'tribike3',
		['price'] = 520,
		['category'] = 'cycles',
		['hash'] = `tribike3`,
		['shop'] = 'pdm',
	},
	--- Motorcycles
	['akuma'] = {
		['name'] = 'Akuma',
		['brand'] = 'Dinka',
		['model'] = 'akuma',
		['price'] = 55000,
		['category'] = 'motorcycles',
		['hash'] = `akuma`,
		['shop'] = 'pdm',
	},
	['avarus'] = {
		['name'] = 'Avarus',
		['brand'] = 'LCC',
		['model'] = 'avarus',
		['price'] = 20000,
		['category'] = 'motorcycles',
		['hash'] = `avarus`,
		['shop'] = 'pdm',
	},
	['bagger'] = {
		['name'] = 'Bagger',
		['brand'] = 'WMC',
		['model'] = 'bagger',
		['price'] = 13500,
		['category'] = 'motorcycles',
		['hash'] = `bagger`,
		['shop'] = 'pdm',
	},
	['bati'] = {
		['name'] = 'Bati 801',
		['brand'] = 'Pegassi',
		['model'] = 'bati',
		['price'] = 24000,
		['category'] = 'motorcycles',
		['hash'] = `bati`,
		['shop'] = 'pdm',
	},
	['bati2'] = {
		['name'] = 'Bati 801RR',
		['brand'] = 'Pegassi',
		['model'] = 'bati2',
		['price'] = 19000,
		['category'] = 'motorcycles',
		['hash'] = `bati2`,
		['shop'] = 'pdm',
	},
	['bf400'] = {
		['name'] = 'BF400',
		['brand'] = 'Nagasaki',
		['model'] = 'bf400',
		['price'] = 22000,
		['category'] = 'motorcycles',
		['hash'] = `bf400`,
		['shop'] = 'pdm',
	},
	['carbonrs'] = {
		['name'] = 'Carbon RS',
		['brand'] = 'Nagasaki',
		['model'] = 'carbonrs',
		['price'] = 22000,
		['category'] = 'motorcycles',
		['hash'] = `carbonrs`,
		['shop'] = 'pdm',
	},
	['cliffhanger'] = {
		['name'] = 'Cliffhanger',
		['brand'] = 'Western',
		['model'] = 'cliffhanger',
		['price'] = 28500,
		['category'] = 'motorcycles',
		['hash'] = `cliffhanger`,
		['shop'] = 'pdm',
	},
	['daemon'] = {
		['name'] = 'Daemon',
		['brand'] = 'WMC',
		['model'] = 'daemon',
		['price'] = 14000,
		['category'] = 'motorcycles',
		['hash'] = `daemon`,
		['shop'] = 'pdm',
	},
	['daemon2'] = {
		['name'] = 'Daemon Custom',
		['brand'] = 'Western',
		['model'] = 'daemon2',
		['price'] = 23000,
		['category'] = 'motorcycles',
		['hash'] = `daemon2`,
		['shop'] = 'pdm',
	},
	['defiler'] = {
		['name'] = 'Defiler',
		['brand'] = 'Shitzu',
		['model'] = 'defiler',
		['price'] = 30000,
		['category'] = 'motorcycles',
		['hash'] = `defiler`,
		['shop'] = 'pdm',
	},
	['diablous'] = {
		['name'] = 'Diablous',
		['brand'] = 'Principe',
		['model'] = 'diablous',
		['price'] = 30000,
		['category'] = 'motorcycles',
		['hash'] = `diablous`,
		['shop'] = 'pdm',
	},
	['diablous2'] = {
		['name'] = 'Diablous Custom',
		['brand'] = 'Principe',
		['model'] = 'diablous2',
		['price'] = 38000,
		['category'] = 'motorcycles',
		['hash'] = `diablous2`,
		['shop'] = 'pdm',
	},
	['double'] = {
		['name'] = 'Double-T',
		['brand'] = 'Dinka',
		['model'] = 'double',
		['price'] = 28000,
		['category'] = 'motorcycles',
		['hash'] = `double`,
		['shop'] = 'pdm',
	},
	['enduro'] = {
		['name'] = 'Enduro',
		['brand'] = 'Dinka',
		['model'] = 'enduro',
		['price'] = 5500,
		['category'] = 'motorcycles',
		['hash'] = `enduro`,
		['shop'] = 'pdm',
	},
	['esskey'] = {
		['name'] = 'Esskey',
		['brand'] = 'Pegassi',
		['model'] = 'esskey',
		['price'] = 12000,
		['category'] = 'motorcycles',
		['hash'] = `esskey`,
		['shop'] = 'pdm',
	},
	['faggio'] = {
		['name'] = 'Faggio Sport',
		['brand'] = 'Pegassi',
		['model'] = 'faggio',
		['price'] = 2000,
		['category'] = 'motorcycles',
		['hash'] = `faggio`,
		['shop'] = 'pdm',
	},
	['faggio2'] = {
		['name'] = 'Faggio',
		['brand'] = 'Pegassi',
		['model'] = 'faggio2',
		['price'] = 1900,
		['category'] = 'motorcycles',
		['hash'] = `faggio2`,
		['shop'] = 'pdm',
	},
	['faggio3'] = {
		['name'] = 'Faggio Mod',
		['brand'] = 'Pegassi',
		['model'] = 'faggio3',
		['price'] = 2500,
		['category'] = 'motorcycles',
		['hash'] = `faggio3`,
		['shop'] = 'pdm',
	},
	['fcr'] = {
		['name'] = 'FCR 1000',
		['brand'] = 'Pegassi',
		['model'] = 'fcr',
		['price'] = 5000,
		['category'] = 'motorcycles',
		['hash'] = `fcr`,
		['shop'] = 'pdm',
	},
	['fcr2'] = {
		['name'] = 'FCR 1000 Custom',
		['brand'] = 'Pegassi',
		['model'] = 'fcr2',
		['price'] = 19000,
		['category'] = 'motorcycles',
		['hash'] = `fcr2`,
		['shop'] = 'pdm',
	},
	['hakuchou'] = {
		['name'] = 'Hakuchou',
		['brand'] = 'Shitzu',
		['model'] = 'hakuchou',
		['price'] = 17000,
		['category'] = 'motorcycles',
		['hash'] = `hakuchou`,
		['shop'] = 'pdm',
	},
	['hakuchou2'] = {
		['name'] = 'Hakuchou Drag',
		['brand'] = 'Shitzu',
		['model'] = 'hakuchou2',
		['price'] = 45000,
		['category'] = 'motorcycles',
		['hash'] = `hakuchou2`,
		['shop'] = 'pdm',
	},
	['hexer'] = {
		['name'] = 'Hexer',
		['brand'] = 'LCC',
		['model'] = 'hexer',
		['price'] = 16000,
		['category'] = 'motorcycles',
		['hash'] = `hexer`,
		['shop'] = 'pdm',
	},
	['innovation'] = {
		['name'] = 'Innovation',
		['brand'] = 'LLC',
		['model'] = 'innovation',
		['price'] = 33500,
		['category'] = 'motorcycles',
		['hash'] = `innovation`,
		['shop'] = 'pdm',
	},
	['lectro'] = {
		['name'] = 'Lectro',
		['brand'] = 'Principe',
		['model'] = 'lectro',
		['price'] = 28000,
		['category'] = 'motorcycles',
		['hash'] = `lectro`,
		['shop'] = 'pdm',
	},
	['manchez'] = {
		['name'] = 'Manchez',
		['brand'] = 'Maibatsu',
		['model'] = 'manchez',
		['price'] = 8300,
		['category'] = 'motorcycles',
		['hash'] = `manchez`,
		['shop'] = 'pdm',
	},
	['nemesis'] = {
		['name'] = 'Nemesis',
		['brand'] = 'Principe',
		['model'] = 'nemesis',
		['price'] = 20000,
		['category'] = 'motorcycles',
		['hash'] = `nemesis`,
		['shop'] = 'pdm',
	},
	['nightblade'] = {
		['name'] = 'Nightblade',
		['brand'] = 'WMC',
		['model'] = 'nightblade',
		['price'] = 23000,
		['category'] = 'motorcycles',
		['hash'] = `nightblade`,
		['shop'] = 'pdm',
	},
	['pcj'] = {
		['name'] = 'PCJ-600',
		['brand'] = 'Shitzu',
		['model'] = 'pcj',
		['price'] = 15000,
		['category'] = 'motorcycles',
		['hash'] = `pcj`,
		['shop'] = 'pdm',
	},
	['ratbike'] = {
		['name'] = 'Rat Bike',
		['brand'] = 'Western',
		['model'] = 'ratbike',
		['price'] = 3000,
		['category'] = 'motorcycles',
		['hash'] = `ratbike`,
		['shop'] = 'pdm',
	},
	['ruffian'] = {
		['name'] = 'Ruffian',
		['brand'] = 'Pegassi',
		['model'] = 'ruffian',
		['price'] = 25000,
		['category'] = 'motorcycles',
		['hash'] = `ruffian`,
		['shop'] = 'pdm',
	},
	['sanchez'] = {
		['name'] = 'Sanchez Livery',
		['brand'] = 'Maibatsu',
		['model'] = 'sanchez',
		['price'] = 5300,
		['category'] = 'motorcycles',
		['hash'] = `sanchez`,
		['shop'] = 'pdm',
	},
	['sanchez2'] = {
		['name'] = 'Sanchez',
		['brand'] = 'Maibatsu',
		['model'] = 'sanchez2',
		['price'] = 5300,
		['category'] = 'motorcycles',
		['hash'] = `sanchez2`,
		['shop'] = 'pdm',
	},
	['sanctus'] = {
		['name'] = 'Sanctus',
		['brand'] = 'LCC',
		['model'] = 'sanctus',
		['price'] = 35000,
		['category'] = 'motorcycles',
		['hash'] = `sanctus`,
		['shop'] = 'pdm',
	},
	['sovereign'] = {
		['name'] = 'Sovereign',
		['brand'] = 'WMC',
		['model'] = 'sovereign',
		['price'] = 8000,
		['category'] = 'motorcycles',
		['hash'] = `sovereign`,
		['shop'] = 'pdm',
	},
	['vader'] = {
		['name'] = 'Vader',
		['brand'] = 'Shitzu',
		['model'] = 'vader',
		['price'] = 7200,
		['category'] = 'motorcycles',
		['hash'] = `vader`,
		['shop'] = 'pdm',
	},
	['vortex'] = {
		['name'] = 'Vortex',
		['brand'] = 'Pegassi',
		['model'] = 'vortex',
		['price'] = 31000,
		['category'] = 'motorcycles',
		['hash'] = `vortex`,
		['shop'] = 'pdm',
	},
	['wolfsbane'] = {
		['name'] = 'Wolfsbane',
		['brand'] = 'Western',
		['model'] = 'wolfsbane',
		['price'] = 14000,
		['category'] = 'motorcycles',
		['hash'] = `wolfsbane`,
		['shop'] = 'pdm',
	},
	['zombiea'] = {
		['name'] = 'Zombie Bobber',
		['brand'] = 'Western',
		['model'] = 'zombiea',
		['price'] = 28000,
		['category'] = 'motorcycles',
		['hash'] = `zombiea`,
		['shop'] = 'pdm',
	},
	['zombieb'] = {
		['name'] = 'Zombie Chopper',
		['brand'] = 'Western',
		['model'] = 'zombieb',
		['price'] = 27000,
		['category'] = 'motorcycles',
		['hash'] = `zombieb`,
		['shop'] = 'pdm',
	},
	['manchez2'] = {
		['name'] = 'Manchez',
		['brand'] = 'Maibatsu',
		['model'] = 'manchez2',
		['price'] = 14000,
		['category'] = 'motorcycles',
		['hash'] = `manchez2`,
		['shop'] = 'pdm',
	},
	['shinobi'] = {		--DLC +set sv_enforceGameBuild 2545
		['name'] = 'Shinobi',
		['brand'] = 'Nagasaki',
		['model'] = 'shinobi',
		['price'] = 25000,
		['category'] = 'motorcycles',
		['hash'] = `shinobi`,
		['shop'] = 'pdm',
	},
	['reever'] = {		--DLC +set sv_enforceGameBuild 2545
		['name'] = 'Reever',
		['brand'] = 'Western',
		['model'] = 'reever',
		['price'] = 25000,
		['category'] = 'motorcycles',
		['hash'] = `reever`,
		['shop'] = 'pdm',
	},
	--- Muscle
	['blade'] = {
		['name'] = 'Blade',
		['brand'] = 'Vapid',
		['model'] = 'blade',
		['price'] = 23500,
		['category'] = 'muscle',
		['hash'] = `blade`,
		['shop'] = 'pdm',
	},
	['buccaneer'] = {
		['name'] = 'Buccaneer',
		['brand'] = 'Albany',
		['model'] = 'buccaneer',
		['price'] = 22500,
		['category'] = 'muscle',
		['hash'] = `buccaneer`,
		['shop'] = 'pdm',
	},
	['buccaneer2'] = {
		['name'] = 'Buccaneer Rider',
		['brand'] = 'Albany',
		['model'] = 'buccaneer2',
		['price'] = 24500,
		['category'] = 'muscle',
		['hash'] = `buccaneer2`,
		['shop'] = 'pdm',
	},
	['chino'] = {
		['name'] = 'Chino',
		['brand'] = 'Vapid',
		['model'] = 'chino',
		['price'] = 5000,
		['category'] = 'muscle',
		['hash'] = `chino`,
		['shop'] = 'pdm',
	},
	['chino2'] = {
		['name'] = 'Chino Luxe',
		['brand'] = 'Vapid',
		['model'] = 'chino2',
		['price'] = 8000,
		['category'] = 'muscle',
		['hash'] = `chino2`,
		['shop'] = 'pdm',
	},
	['clique'] = {							--DLC
		['name'] = 'Clique',
		['brand'] = 'Vapid',
		['model'] = 'clique',
		['price'] = 20000,
		['category'] = 'muscle',
		['hash'] = `clique`,
		['shop'] = 'pdm',
	},
	['coquette3'] = {
		['name'] = 'Coquette BlackFin',
		['brand'] = 'Invetero',
		['model'] = 'coquette3',
		['price'] = 180000,
		['category'] = 'muscle',
		['hash'] = `coquette3`,
		['shop'] = 'pdm',
	},
	['deviant'] = {							--DLC
		['name'] = 'Deviant',
		['brand'] = 'Schyster',
		['model'] = 'deviant',
		['price'] = 70000,
		['category'] = 'muscle',
		['hash'] = `deviant`,
		['shop'] = 'pdm',
	},
	['dominator'] = {
		['name'] = 'Dominator',
		['brand'] = 'Vapid',
		['model'] = 'dominator',
		['price'] = 62500,
		['category'] = 'muscle',
		['hash'] = `dominator`,
		['shop'] = 'pdm',
	},
	['dominator2'] = {
		['name'] = 'Pißwasser Dominator',
		['brand'] = 'Vapid',
		['model'] = 'dominator2',
		['price'] = 50000,
		['category'] = 'muscle',
		['hash'] = `dominator2`,
		['shop'] = 'pdm',
	},
	['dominator3'] = {
		['name'] = 'Dominator GTX',
		['brand'] = 'Vapid',
		['model'] = 'dominator3',
		['price'] = 70000,
		['category'] = 'muscle',
		['hash'] = `dominator3`,
		['shop'] = 'pdm',
	},
	['dominator7'] = {							--DLC +set sv_enforceGameBuild 2372
		['name'] = 'Dominator ASP',
		['brand'] = 'Vapid',
		['model'] = 'dominator7',
		['price'] = 110000,
		['category'] = 'muscle',
		['hash'] = `dominator7`,
		['shop'] = 'pdm',
	},
	['dominator8'] = {							--DLC +set sv_enforceGameBuild 2372
		['name'] = 'Dominator GTT',
		['brand'] = 'Vapid',
		['model'] = 'dominator8',
		['price'] = 80000,
		['category'] = 'muscle',
		['hash'] = `dominator8`,
		['shop'] = 'pdm',
	},
	['dukes'] = {
		['name'] = 'Dukes',
		['brand'] = 'Imponte',
		['model'] = 'dukes',
		['price'] = 23500,
		['category'] = 'muscle',
		['hash'] = `dukes`,
		['shop'] = 'pdm',
	},
	['dukes3'] = {
		['name'] = 'Beater Dukes',
		['brand'] = 'Imponte',
		['model'] = 'dukes3',
		['price'] = 45000,
		['category'] = 'muscle',
		['hash'] = `dukes3`,
		['shop'] = 'pdm',
	},
	['faction'] = {
		['name'] = 'Faction',
		['brand'] = 'Willard',
		['model'] = 'faction',
		['price'] = 17000,
		['category'] = 'muscle',
		['hash'] = `faction`,
		['shop'] = 'pdm',
	},
	['faction2'] = {
		['name'] = 'Faction Rider',
		['brand'] = 'Willard',
		['model'] = 'faction2',
		['price'] = 19000,
		['category'] = 'muscle',
		['hash'] = `faction2`,
		['shop'] = 'pdm',
	},
	['ellie'] = {
		['name'] = 'Ellie',
		['brand'] = 'Vapid',
		['model'] = 'ellie',
		['price'] = 42250,
		['category'] = 'muscle',
		['hash'] = `ellie`,
		['shop'] = 'pdm',
	},
	['gauntlet'] = {
		['name'] = 'Gauntlet',
		['brand'] = 'Bravado',
		['model'] = 'gauntlet',
		['price'] = 28500,
		['category'] = 'muscle',
		['hash'] = `gauntlet`,
		['shop'] = 'pdm',
	},
	['gauntlet2'] = {
		['name'] = 'Redwood Gauntlet',
		['brand'] = 'Bravado',
		['model'] = 'gauntlet2',
		['price'] = 70000,
		['category'] = 'muscle',
		['hash'] = `gauntlet2`,
		['shop'] = 'pdm',
	},
	['gauntlet3'] = {							--DLC
		['name'] = 'Classic Gauntlet',
		['brand'] = 'Bravado',
		['model'] = 'gauntlet3',
		['price'] = 75000,
		['category'] = 'muscle',
		['hash'] = `gauntlet3`,
		['shop'] = 'pdm',
	},
	['gauntlet4'] = {							--DLC
		['name'] = 'Gauntlet Hellfire',
		['brand'] = 'Bravado',
		['model'] = 'gauntlet4',
		['price'] = 80000,
		['category'] = 'muscle',
		['hash'] = `gauntlet4`,
		['shop'] = 'pdm',
	},
	['gauntlet5'] = {
		['name'] = 'Gauntlet Classic Custom',
		['brand'] = 'Bravado',
		['model'] = 'gauntlet5',
		['price'] = 120000,
		['category'] = 'muscle',
		['hash'] = `gauntlet5`,
		['shop'] = 'pdm',
	},
	['hermes'] = {
		['name'] = 'Hermes',
		['brand'] = 'Albany',
		['model'] = 'hermes',
		['price'] = 535000,
		['category'] = 'muscle',
		['hash'] = `hermes`,
		['shop'] = 'pdm',
	},
	['hotknife'] = {
		['name'] = 'Hotknife',
		['brand'] = 'Vapid',
		['model'] = 'hotknife',
		['price'] = 90000,
		['category'] = 'muscle',
		['hash'] = `hotknife`,
		['shop'] = 'pdm',
	},
	['hustler'] = {
		['name'] = 'Hustler',
		['brand'] = 'Vapid',
		['model'] = 'hustler',
		['price'] = 95000,
		['category'] = 'muscle',
		['hash'] = `hustler`,
		['shop'] = 'pdm',
	},
	['impaler'] = {							--DLC
		['name'] = 'impaler',
		['brand'] = 'Vapid',
		['model'] = 'impaler',
		['price'] = 95000,
		['category'] = 'muscle',
		['hash'] = `impaler`,
		['shop'] = 'pdm',
	},
	['imperator'] = {							--DLC
		['name'] = 'imperator',
		['brand'] = 'Vapid',
		['model'] = 'imperator',
		['price'] = 95000,
		['category'] = 'muscle',
		['hash'] = `imperator`,
		['shop'] = 'pdm',
	},
	['lurcher'] = {
		['name'] = 'Gauntlet Classic Custom',
		['brand'] = 'Bravado',
		['model'] = 'lurcher',
		['price'] = 21000,
		['category'] = 'muscle',
		['hash'] = `lurcher`,
		['shop'] = 'pdm',
	},
	['moonbeam'] = {
		['name'] = 'Moonbeam',
		['brand'] = 'Declasse',
		['model'] = 'moonbeam',
		['price'] = 13000,
		['category'] = 'vans',
		['hash'] = `moonbeam`,
		['shop'] = 'pdm',
	},
	['moonbeam2'] = {
		['name'] = 'Moonbeam Custom',
		['brand'] = 'Declasse',
		['model'] = 'moonbeam2',
		['price'] = 15000,
		['category'] = 'vans',
		['hash'] = `moonbeam2`,
		['shop'] = 'pdm',
	},
	['nightshade'] = {
		['name'] = 'Nightshade',
		['brand'] = 'Imponte',
		['model'] = 'nightshade',
		['price'] = 70000,
		['category'] = 'muscle',
		['hash'] = `nightshade`,
		['shop'] = 'pdm',
	},
	['peyote2'] = {							--DLC
		['name'] = 'Peyote Gasser',
		['brand'] = 'Vapid',
		['model'] = 'peyote2',
		['price'] = 40000,
		['category'] = 'sportsclassics',
		['hash'] = `peyote2`,
		['shop'] = 'pdm',
	},
	['phoenix'] = {
		['name'] = 'Phoenix',
		['brand'] = 'Imponte',
		['model'] = 'phoenix',
		['price'] = 65000,
		['category'] = 'muscle',
		['hash'] = `phoenix`,
		['shop'] = 'pdm',
	},
	['picador'] = {
		['name'] = 'Picador',
		['brand'] = 'Cheval',
		['model'] = 'picador',
		['price'] = 20000,
		['category'] = 'muscle',
		['hash'] = `picador`,
		['shop'] = 'pdm',
	},
	['ratloader2'] = {
		['name'] = 'ratloader2',
		['brand'] = 'Ratloader2',
		['model'] = 'ratloader2',
		['price'] = 20000,
		['category'] = 'muscle',
		['hash'] = `ratloader2`,
		['shop'] = 'pdm',
	},
	['ruiner'] = {
		['name'] = 'Ruiner',
		['brand'] = 'Imponte',
		['model'] = 'ruiner',
		['price'] = 29000,
		['category'] = 'muscle',
		['hash'] = `ruiner`,
		['shop'] = 'pdm',
	},
	['sabregt'] = {
		['name'] = 'Sabre Turbo',
		['brand'] = 'Declasse',
		['model'] = 'sabregt',
		['price'] = 23000,
		['category'] = 'muscle',
		['hash'] = `sabregt`,
		['shop'] = 'pdm',
	},
	['sabregt2'] = {
		['name'] = 'Sabre GT',
		['brand'] = 'Declasse',
		['model'] = 'sabregt2',
		['price'] = 26500,
		['category'] = 'muscle',
		['hash'] = `sabregt2`,
		['shop'] = 'pdm',
	},
	['slamvan'] = {
		['name'] = 'Slam Van',
		['brand'] = 'Vapid',
		['model'] = 'slamvan',
		['price'] = 30000,
		['category'] = 'muscle',
		['hash'] = `slamvan`,
		['shop'] = 'pdm',
	},
	['slamvan2'] = {
		['name'] = 'Lost Slam Van',
		['brand'] = 'Vapid',
		['model'] = 'slamvan2',
		['price'] = 90000,
		['category'] = 'muscle',
		['hash'] = `slamvan2`,
		['shop'] = 'pdm',
	},
	['slamvan3'] = {
		['name'] = 'Slam Van Custom',
		['brand'] = 'Vapid',
		['model'] = 'slamvan3',
		['price'] = 17000,
		['category'] = 'muscle',
		['hash'] = `slamvan3`,
		['shop'] = 'pdm',
	},
	['stalion'] = {
		['name'] = 'Stallion',
		['brand'] = 'Declasse',
		['model'] = 'stalion',
		['price'] = 33000,
		['category'] = 'muscle',
		['hash'] = `stalion`,
		['shop'] = 'pdm',
	},
	['stalion2'] = {
		['name'] = 'Stallion Burgershot',
		['brand'] = 'Declasse',
		['model'] = 'stalion2',
		['price'] = 40000,
		['category'] = 'muscle',
		['hash'] = `stalion2`,
		['shop'] = 'pdm',
	},
	['tampa'] = {
		['name'] = 'Tampa',
		['brand'] = 'Declasse',
		['model'] = 'tampa',
		['price'] = 24500,
		['category'] = 'muscle',
		['hash'] = `tampa`,
		['shop'] = 'pdm',
	},
	['tulip'] = {							--DLC
		['name'] = 'Tulip',
		['brand'] = 'Declasse',
		['model'] = 'tulip',
		['price'] = 80000,
		['category'] = 'muscle',
		['hash'] = `tulip`,
		['shop'] = 'pdm',
	},
	['vamos'] = {							--DLC
		['name'] = 'Vamos',
		['brand'] = 'Declasse',
		['model'] = 'vamos',
		['price'] = 30000,
		['category'] = 'muscle',
		['hash'] = `vamos`,
		['shop'] = 'pdm',
	},
	['vigero'] = {
		['name'] = 'Vigero',
		['brand'] = 'Declasse',
		['model'] = 'vigero',
		['price'] = 39500,
		['category'] = 'muscle',
		['hash'] = `vigero`,
		['shop'] = 'pdm',
	},
	['voodoo'] = {
		['name'] = 'Voodoo',
		['brand'] = 'Declasse',
		['model'] = 'voodoo',
		['price'] = 13000,
		['category'] = 'muscle',
		['hash'] = `voodoo`,
		['shop'] = 'pdm',
	},
	['yosemite'] = {
		['name'] = 'Yosemite',
		['brand'] = 'Declasse',
		['model'] = 'yosemite',
		['price'] = 19500,
		['category'] = 'muscle',
		['hash'] = `yosemite`,
		['shop'] = 'pdm',
	},
	['yosemite2'] = {
		['name'] = 'Yosemite Drift',
		['brand'] = 'Declasse',
		['model'] = 'yosemite2',
		['price'] = 55000,
		['category'] = 'muscle',
		['hash'] = `yosemite2`,
		['shop'] = 'pdm',
	},
	['yosemite3'] = {
		['name'] = 'Yosemite Rancher',
		['brand'] = 'Declasse',
		['price'] = 425000,
		['category'] = 'offroad',
		['model'] = 'yosemite3',
		['hash'] = `yosemite3`,
		['shop'] = 'pdm',
	},
	['buffalo4'] = { 	 	--DLC +set sv_enforceGameBuild 2545
		['name'] = 'Buffalo STX',
		['brand'] = 'Bravado',
		['model'] = 'buffalo4',
		['price'] = 345000,
		['category'] = 'muscle',
		['hash'] = `buffalo4`,
		['shop'] = 'pdm',
	},
	--- Off-Road
	['bfinjection'] = {
		['name'] = 'Bf Injection',
		['brand'] = 'Annis',
		['price'] = 9000,
		['category'] = 'offroad',
		['model'] = 'bfinjection',
		['hash'] = `bfinjection`,
		['shop'] = 'pdm',
	},
	['bifta'] = {
		['name'] = 'Bifta',
		['brand'] = 'Annis',
		['price'] = 15500,
		['category'] = 'offroad',
		['model'] = 'bifta',
		['hash'] = `bifta`,
		['shop'] = 'pdm',
	},
	['blazer'] = {
		['name'] = 'Blazer',
		['brand'] = 'Annis',
		['price'] = 7500,
		['category'] = 'offroad',
		['model'] = 'blazer',
		['hash'] = `blazer`,
		['shop'] = 'pdm',
	},
	['blazer3'] = {
		['name'] = 'Blazer Hot Rod',
		['brand'] = 'Nagasaki',
		['model'] = 'blazer3',
		['price'] = 7000,
		['category'] = 'offroad',
		['hash'] = `blazer3`,
		['shop'] = 'pdm',
	},
	['blazer4'] = {
		['name'] = 'Blazer Sport',
		['brand'] = 'Annis',
		['price'] = 9250,
		['category'] = 'offroad',
		['model'] = 'blazer4',
		['hash'] = `blazer4`,
		['shop'] = 'pdm',
	},
	['caracara2'] = {							--DLC
		['name'] = 'Caracara 4x4',
		['brand'] = 'Vapid',
		['model'] = 'caracara2',
		['price'] = 80000,
		['category'] = 'offroad',
		['hash'] = `caracara2`,
		['shop'] = 'pdm',
	},
	['dubsta3'] = {
		['name'] = 'Dubsta 6x6',
		['brand'] = 'Annis',
		['price'] = 34000,
		['category'] = 'offroad',
		['model'] = 'dubsta3',
		['hash'] = `dubsta3`,
		['shop'] = 'pdm',
	},
	['dune'] = {
		['name'] = 'Dune Buggy',
		['brand'] = 'Annis',
		['price'] = 14000,
		['category'] = 'offroad',
		['model'] = 'dune',
		['hash'] = `dune`,
		['shop'] = 'pdm',
	},
	['everon'] = {
		['name'] = 'Everon',
		['brand'] = 'Karin',
		['model'] = 'everon',
		['price'] = 60000,
		['category'] = 'offroad',
		['hash'] = `everon`,
		['shop'] = 'pdm',
	},
	['hellion'] = {							--DLC
		['name'] = 'Hellion',
		['brand'] = 'Annis',
		['model'] = 'hellion',
		['price'] = 38000,
		['category'] = 'offroad',
		['hash'] = `hellion`,
		['shop'] = 'pdm',
	},
	['kalahari'] = {
		['name'] = 'Kalahari',
		['brand'] = 'Canis',
		['model'] = 'kalahari',
		['price'] = 14000,
		['category'] = 'offroad',
		['hash'] = `kalahari`,
		['shop'] = 'pdm',
	},
	['kamacho'] = {
		['name'] = 'Kamacho',
		['brand'] = 'Canis',
		['model'] = 'kamacho',
		['price'] = 50000,
		['category'] = 'offroad',
		['hash'] = `kamacho`,
		['shop'] = 'pdm',
	},
	['mesa3'] = {
		['name'] = 'Mesa Merryweather',
		['brand'] = 'Canis',
		['model'] = 'mesa3',
		['price'] = 400000,
		['category'] = 'offroad',
		['hash'] = `mesa3`,
		['shop'] = 'pdm',
	},
	['outlaw'] = {
		['name'] = 'Outlaw',
		['brand'] = 'Nagasaki',
		['model'] = 'outlaw',
		['price'] = 15000,
		['category'] = 'offroad',
		['hash'] = `outlaw`,
		['shop'] = 'pdm',
	},
	['rancherxl'] = {
		['name'] = 'Rancher XL',
		['brand'] = 'Declasse',
		['model'] = 'rancherxl',
		['price'] = 24000,
		['category'] = 'offroad',
		['hash'] = `rancherxl`,
		['shop'] = 'pdm',
	},
	['rebel2'] = {
		['name'] = 'Rebel',
		['brand'] = 'Annis',
		['model'] = 'rebel2',
		['price'] = 20000,
		['category'] = 'offroad',
		['hash'] = `rebel2`,
		['shop'] = 'pdm',
	},
	['sandking'] = {
		['name'] = 'Sandking',
		['brand'] = 'Annis',
		['price'] = 25000,
		['category'] = 'offroad',
		['model'] = 'sandking',
		['hash'] = `sandking`,
		['shop'] = 'pdm',
	},
	['sandking2'] = {
		['name'] = 'Sandking SWB',
		['brand'] = 'Annis',
		['price'] = 38000,
		['category'] = 'offroad',
		['model'] = 'sandking2',
		['hash'] = `sandking2`,
		['shop'] = 'pdm',
	},
	['trophytruck'] = {
		['name'] = 'Trophy Truck',
		['brand'] = 'Annis',
		['price'] = 60000,
		['category'] = 'offroad',
		['model'] = 'trophytruck',
		['hash'] = `trophytruck`,
		['shop'] = 'pdm',
	},
	['vagrant'] = {
		['name'] = 'Vagrant',
		['brand'] = 'Maxwell',
		['price'] = 50000,
		['category'] = 'offroad',
		['model'] = 'vagrant',
		['hash'] = `vagrant`,
		['shop'] = 'pdm',
	},
	['verus'] = {
		['name'] = 'Verus',
		['brand'] = 'Dinka',
		['price'] = 20000,
		['category'] = 'offroad',
		['model'] = 'verus',
		['hash'] = `verus`,
		['shop'] = 'pdm',
	},
	['winky'] = {
		['name'] = 'Winky',
		['brand'] = 'Vapid',
		['price'] = 10000,
		['category'] = 'offroad',
		['model'] = 'winky',
		['hash'] = `winky`,
		['shop'] = 'pdm',
	},
	--- SUVs
	['baller'] = {
		['name'] = 'Baller',
		['brand'] = 'Gallivanter',
		['model'] = 'baller',
		['price'] = 22000,
		['category'] = 'suvs',
		['hash'] = `baller`,
		['shop'] = 'pdm',
	},
	['baller2'] = {
		['name'] = 'Baller',
		['brand'] = 'Gallivanter',
		['model'] = 'baller2',
		['price'] = 15000,
		['category'] = 'suvs',
		['hash'] = `baller2`,
		['shop'] = 'pdm',
	},
	['baller3'] = {
		['name'] = 'Baller LE',
		['brand'] = 'Gallivanter',
		['model'] = 'baller3',
		['price'] = 15000,
		['category'] = 'suvs',
		['hash'] = `baller3`,
		['shop'] = 'pdm',
	},
	['baller4'] = {
		['name'] = 'Baller LE LWB',
		['brand'] = 'Gallivanter',
		['model'] = 'baller4',
		['price'] = 29000,
		['category'] = 'suvs',
		['hash'] = `baller4`,
		['shop'] = 'pdm',
	},
	['bjxl'] = {
		['name'] = 'BeeJay XL',
		['brand'] = 'Karin',
		['model'] = 'bjxl',
		['price'] = 19000,
		['category'] = 'suvs',
		['hash'] = `bjxl`,
		['shop'] = 'pdm',
	},
	['cavalcade'] = {
		['name'] = 'Cavalcade',
		['brand'] = 'Albany',
		['model'] = 'cavalcade',
		['price'] = 14000,
		['category'] = 'suvs',
		['hash'] = `cavalcade`,
		['shop'] = 'pdm',
	},
	['cavalcade2'] = {
		['name'] = 'Cavalcade',
		['brand'] = 'Albany',
		['model'] = 'cavalcade2',
		['price'] = 16500,
		['category'] = 'suvs',
		['hash'] = `cavalcade2`,
		['shop'] = 'pdm',
	},
	['contender'] = {
		['name'] = 'Contender',
		['brand'] = 'Vapid',
		['model'] = 'contender',
		['price'] = 35000,
		['category'] = 'suvs',
		['hash'] = `contender`,
		['shop'] = 'pdm',
	},
	['dubsta'] = {
		['name'] = 'Dubsta',
		['brand'] = 'Benefactor',
		['model'] = 'dubsta',
		['price'] = 19000,
		['category'] = 'suvs',
		['hash'] = `dubsta`,
		['shop'] = 'pdm',
	},
	['dubsta2'] = {
		['name'] = 'Dubsta Luxuary',
		['brand'] = 'Benefactor',
		['model'] = 'dubsta2',
		['price'] = 19500,
		['category'] = 'suvs',
		['hash'] = `dubsta2`,
		['shop'] = 'pdm',
	},
	['fq2'] = {
		['name'] = 'FQ2',
		['brand'] = 'Fathom',
		['model'] = 'fq2',
		['price'] = 18500,
		['category'] = 'suvs',
		['hash'] = `fq2`,
		['shop'] = 'pdm',
	},
	['granger'] = {
		['name'] = 'Granger',
		['brand'] = 'Declasse',
		['model'] = 'granger',
		['price'] = 22000,
		['category'] = 'suvs',
		['hash'] = `granger`,
		['shop'] = 'pdm',
	},
	['gresley'] = {
		['name'] = 'Gresley',
		['brand'] = 'Bravado',
		['model'] = 'gresley',
		['price'] = 25000,
		['category'] = 'suvs',
		['hash'] = `gresley`,
		['shop'] = 'pdm',
	},
	['habanero'] = {
		['name'] = 'Habanero',
		['brand'] = 'Emperor',
		['model'] = 'habanero',
		['price'] = 20000,
		['category'] = 'suvs',
		['hash'] = `habanero`,
		['shop'] = 'pdm',
	},
	['huntley'] = {
		['name'] = 'Huntley S',
		['brand'] = 'Enus',
		['model'] = 'huntley',
		['price'] = 24500,
		['category'] = 'suvs',
		['hash'] = `huntley`,
		['shop'] = 'pdm',
	},
	['landstalker'] = {
		['name'] = 'Landstalker',
		['brand'] = 'Dundreary',
		['model'] = 'landstalker',
		['price'] = 12000,
		['category'] = 'suvs',
		['hash'] = `landstalker`,
		['shop'] = 'pdm',
	},
	['landstalker2'] = {
		['name'] = 'Landstalker XL',
		['brand'] = 'Dundreary',
		['model'] = 'landstalker2',
		['price'] = 26000,
		['category'] = 'suvs',
		['hash'] = `landstalker2`,
		['shop'] = 'pdm',
	},
	['mesa'] = {
		['name'] = 'Mesa',
		['brand'] = 'Canis',
		['model'] = 'mesa',
		['price'] = 12000,
		['category'] = 'offroad',
		['hash'] = `mesa`,
		['shop'] = 'pdm',
	},
	['novak'] = {							--DLC
		['name'] = 'Novak',
		['brand'] = 'Lampadati',
		['model'] = 'novak',
		['price'] = 70000,
		['category'] = 'suvs',
		['hash'] = `novak`,
		['shop'] = 'pdm',
	},
	['patriot'] = {
		['name'] = 'Patriot',
		['brand'] = 'Mammoth',
		['model'] = 'patriot',
		['price'] = 21000,
		['category'] = 'suvs',
		['hash'] = `patriot`,
		['shop'] = 'pdm',
	},
	['radi'] = {
		['name'] = 'Radius',
		['brand'] = 'Vapid',
		['model'] = 'radi',
		['price'] = 18000,
		['category'] = 'suvs',
		['hash'] = `radi`,
		['shop'] = 'pdm',
	},
	['rebla'] = {
		['name'] = 'Rebla GTS',
		['brand'] = 'Übermacht',
		['model'] = 'rebla',
		['price'] = 21000,
		['category'] = 'suvs',
		['hash'] = `rebla`,
		['shop'] = 'pdm',
	},
	['rocoto'] = {
		['name'] = 'Rocoto',
		['brand'] = 'Obey',
		['model'] = 'rocoto',
		['price'] = 13000,
		['category'] = 'suvs',
		['hash'] = `rocoto`,
		['shop'] = 'pdm',
	},
	['seminole'] = {
		['name'] = 'Seminole',
		['brand'] = 'Canis',
		['model'] = 'seminole',
		['price'] = 20000,
		['category'] = 'suvs',
		['hash'] = `seminole`,
		['shop'] = 'pdm',
	},
	['seminole2'] = {
		['name'] = 'Seminole Frontier',
		['brand'] = 'Canis',
		['model'] = 'seminole2',
		['price'] = 13000,
		['category'] = 'suvs',
		['hash'] = `seminole2`,
		['shop'] = 'pdm',
	},
	['serrano'] = {
		['name'] = 'Serrano',
		['brand'] = 'Benefactor',
		['model'] = 'serrano',
		['price'] = 48000,
		['category'] = 'suvs',
		['hash'] = `serrano`,
		['shop'] = 'pdm',
	},
	['toros'] = {							--DLC
		['name'] = 'Toros',
		['brand'] = 'Pegassi',
		['model'] = 'toros',
		['price'] = 65000,
		['category'] = 'suvs',
		['hash'] = `toros`,
		['shop'] = 'pdm',
	},
	['xls'] = {
		['name'] = 'XLS',
		['brand'] = 'Benefactor',
		['model'] = 'xls',
		['price'] = 17000,
		['category'] = 'suvs',
		['hash'] = `xls`,
		['shop'] = 'pdm',
	},
	['granger2'] = { 	 	--DLC +set sv_enforceGameBuild 2545
		['name'] = 'Granger 3600LX',
		['brand'] = 'Declasse',
		['model'] = 'granger2',
		['price'] = 221000,
		['category'] = 'suvs',
		['hash'] = `granger2`,
		['shop'] = 'pdm',
	},
	--- Sedans
	['asea'] = {
		['name'] = 'Asea',
		['brand'] = 'Declasse',
		['model'] = 'asea',
		['price'] = 2500,
		['category'] = 'sedans',
		['hash'] = `asea`,
		['shop'] = 'pdm',
	},
	['asterope'] = {
		['name'] = 'Asterope',
		['brand'] = 'Karin',
		['model'] = 'asterope',
		['price'] = 11000,
		['category'] = 'sedans',
		['hash'] = `asterope`,
		['shop'] = 'pdm',
	},
	['cog55'] = {
		['name'] = 'Cognoscenti 55',
		['brand'] = 'Enus',
		['model'] = 'cog55',
		['price'] = 22000,
		['category'] = 'sedans',
		['hash'] = `cog55`,
		['shop'] = 'pdm',
	},
	['cognoscenti'] = {
		['name'] = 'Cognoscenti',
		['brand'] = 'Enus',
		['model'] = 'cognoscenti',
		['price'] = 22500,
		['category'] = 'sedans',
		['hash'] = `cognoscenti`,
		['shop'] = 'pdm',
	},
	['emperor'] = {
		['name'] = 'Emperor',
		['brand'] = 'Albany',
		['model'] = 'emperor',
		['price'] = 4250,
		['category'] = 'sedans',
		['hash'] = `emperor`,
		['shop'] = 'pdm',
	},
	['fugitive'] = {
		['name'] = 'Fugitive',
		['brand'] = 'Cheval',
		['model'] = 'fugitive',
		['price'] = 20000,
		['category'] = 'sedans',
		['hash'] = `fugitive`,
		['shop'] = 'pdm',
	},
	['glendale'] = {
		['name'] = 'Glendale',
		['brand'] = 'Benefactor',
		['model'] = 'glendale',
		['price'] = 3400,
		['category'] = 'sedans',
		['hash'] = `glendale`,
		['shop'] = 'pdm',
	},
	['glendale2'] = {
		['name'] = 'Glendale',
		['brand'] = 'Benefactor',
		['model'] = 'glendale2',
		['price'] = 12000,
		['category'] = 'sedans',
		['hash'] = `glendale2`,
		['shop'] = 'pdm',
	},
	['ingot'] = {
		['name'] = 'Ingot',
		['brand'] = 'Vulcar',
		['model'] = 'ingot',
		['price'] = 4999,
		['category'] = 'sedans',
		['hash'] = `ingot`,
		['shop'] = 'pdm',
	},
	['intruder'] = {
		['name'] = 'Intruder',
		['brand'] = 'Karin',
		['model'] = 'intruder',
		['price'] = 11250,
		['category'] = 'sedans',
		['hash'] = `intruder`,
		['shop'] = 'pdm',
	},
	['premier'] = {
		['name'] = 'Premier',
		['brand'] = 'Declasse',
		['model'] = 'premier',
		['price'] = 12000,
		['category'] = 'sedans',
		['hash'] = `premier`,
		['shop'] = 'pdm',
	},
	['primo'] = {
		['name'] = 'Primo',
		['brand'] = 'Albany',
		['model'] = 'primo',
		['price'] = 5000,
		['category'] = 'sedans',
		['hash'] = `primo`,
		['shop'] = 'pdm',
	},
	['primo2'] = {
		['name'] = 'Primo Custom',
		['brand'] = 'Albany',
		['model'] = 'primo2',
		['price'] = 14500,
		['category'] = 'sedans',
		['hash'] = `primo2`,
		['shop'] = 'pdm',
	},
	['regina'] = {
		['name'] = 'Regina',
		['brand'] = 'Dundreary',
		['model'] = 'regina',
		['price'] = 7000,
		['category'] = 'sedans',
		['hash'] = `regina`,
		['shop'] = 'pdm',
	},
	['stafford'] = {							--DLC
		['name'] = 'Stafford',
		['brand'] = 'Enus',
		['model'] = 'stafford',
		['price'] = 30000,
		['category'] = 'sedans',
		['hash'] = `stafford`,
		['shop'] = 'pdm',
	},
	['stanier'] = {
		['name'] = 'Stanier',
		['brand'] = 'Vapid',
		['model'] = 'stanier',
		['price'] = 19000,
		['category'] = 'sedans',
		['hash'] = `stanier`,
		['shop'] = 'pdm',
	},
	['stratum'] = {
		['name'] = 'Stratum',
		['brand'] = 'Zirconium',
		['model'] = 'stratum',
		['price'] = 15000,
		['category'] = 'sedans',
		['hash'] = `stratum`,
		['shop'] = 'pdm',
	},
	['stretch'] = {
		['name'] = 'Stretch',
		['brand'] = 'Dundreary',
		['model'] = 'stretch',
		['price'] = 19000,
		['category'] = 'sedans',
		['hash'] = `stretch`,
		['shop'] = 'pdm',
	},
	['superd'] = {
		['name'] = 'Super Diamond',
		['brand'] = 'Enus',
		['model'] = 'superd',
		['price'] = 17000,
		['category'] = 'sedans',
		['hash'] = `superd`,
		['shop'] = 'pdm',
	},
	['surge'] = {
		['name'] = 'Surge',
		['brand'] = 'Cheval',
		['model'] = 'surge',
		['price'] = 20000,
		['category'] = 'sedans',
		['hash'] = `surge`,
		['shop'] = 'pdm',
	},
	['tailgater'] = {
		['name'] = 'Tailgater',
		['brand'] = 'Obey',
		['model'] = 'tailgater',
		['price'] = 22000,
		['category'] = 'sedans',
		['hash'] = `tailgater`,
		['shop'] = 'pdm',
	},
	['warrener'] = {
		['name'] = 'Warrener',
		['brand'] = 'Vulcar',
		['model'] = 'warrener',
		['price'] = 4000,
		['category'] = 'sedans',
		['hash'] = `warrener`,
		['shop'] = 'pdm',
	},
	['washington'] = {
		['name'] = 'Washington',
		['brand'] = 'Albany',
		['model'] = 'washington',
		['price'] = 7000,
		['category'] = 'sedans',
		['hash'] = `washington`,
		['shop'] = 'pdm',
	},
	['tailgater2'] = {							--DLC +set sv_enforceGameBuild 2372
		['name'] = 'Tailgater S',
		['brand'] = 'Obey',
		['model'] = 'tailgater2',
		['price'] = 51000,
		['category'] = 'sedans',
		['hash'] = `tailgater2`,
		['shop'] = 'pdm',
	},
	['iwagen'] = { 	 	--DLC +set sv_enforceGameBuild 2545
		['name'] = 'Obey',
		['brand'] = 'I-Wagen',
		['model'] = 'iwagen',
		['price'] = 225000,
		['category'] = 'sedans',
		['hash'] = `iwagen`,
		['shop'] = 'pdm',
	},
	['comet7'] = { 	 	--DLC +set sv_enforceGameBuild 2545
		['name'] = 'Comet',
		['brand'] = 'S2 Cabrio',
		['model'] = 'comet7',
		['price'] = 25000,
		['category'] = 'sedans',
		['hash'] = `comet7`,
		['shop'] = 'pdm',
	},
	['patriot3'] = { 	 	--DLC +set sv_enforceGameBuild 2545
		['name'] = 'Patriot',
		['brand'] = 'Mil-Spec',
		['model'] = 'patriot3',
		['price'] = 270000,
		['category'] = 'sedans',
		['hash'] = `patriot3`,
		['shop'] = 'pdm',
	},
	--- Sports
	['banshee'] = {
		['name'] = 'Banshee',
		['brand'] = 'Bravado',
		['model'] = 'banshee',
		['price'] = 56000,
		['category'] = 'sports',
		['hash'] = `banshee`,
		['shop'] = 'luxury',
	},
	['blista2'] = {
		['name'] = 'Blista Compact',
		['brand'] = 'Dinka',
		['model'] = 'blista2',
		['price'] = 18950,
		['category'] = 'compacts',
		['hash'] = `blista2`,
		['shop'] = 'pdm',
	},
	['buffalo'] = {
		['name'] = 'Buffalo',
		['brand'] = 'Bravado',
		['model'] = 'buffalo',
		['price'] = 18750,
		['category'] = 'sports',
		['hash'] = `buffalo`,
		['shop'] = 'luxury',
	},
	['buffalo2'] = {
		['name'] = 'Buffalo S',
		['brand'] = 'Bravado',
		['model'] = 'buffalo2',
		['price'] = 24500,
		['category'] = 'sports',
		['hash'] = `buffalo2`,
		['shop'] = 'luxury',
	},
	['comet2'] = {
		['name'] = 'Comet',
		['brand'] = 'Pfister',
		['model'] = 'comet2',
		['price'] = 130000,
		['category'] = 'sports',
		['hash'] = `comet2`,
		['shop'] = 'luxury',
	},
	['comet3'] = {
		['name'] = 'Comet Retro Custom',
		['brand'] = 'Pfister',
		['model'] = 'comet3',
		['price'] = 175000,
		['category'] = 'sports',
		['hash'] = `comet3`,
		['shop'] = 'luxury',
	},
	['comet5'] = {
		['name'] = 'Comet SR',
		['brand'] = 'Pfister',
		['model'] = 'comet5',
		['price'] = 155000,
		['category'] = 'sports',
		['hash'] = `comet5`,
		['shop'] = 'luxury',
	},
	['coquette'] = {
		['name'] = 'Coquette',
		['brand'] = 'Invetero',
		['model'] = 'coquette',
		['price'] = 145000,
		['category'] = 'sports',
		['hash'] = `coquette`,
		['shop'] = 'luxury',
	},
	['coquette2'] = {
		['name'] = 'Coquette Classic',
		['brand'] = 'Invetero',
		['model'] = 'coquette2',
		['price'] = 165000,
		['category'] = 'sportsclassics',
		['hash'] = `coquette2`,
		['shop'] = 'pdm',
	},
	['coquette4'] = {
		['name'] = 'Coquette D10',
		['brand'] = 'Invetero',
		['model'] = 'coquette4',
		['price'] = 220000,
		['category'] = 'sports',
		['hash'] = `coquette4`,
		['shop'] = 'luxury',
	},
	['drafter'] = {							--DLC
		['name'] = '8F Drafter',
		['brand'] = 'Obey',
		['model'] = 'drafter',
		['price'] = 80000,
		['category'] = 'sports',
		['hash'] = `drafter`,
		['shop'] = 'luxury',
	},
	['elegy'] = {							--DLC
		['name'] = 'Elegy Retro Custom',
		['brand'] = 'Annis',
		['model'] = 'elegy',
		['price'] = 145000,
		['category'] = 'sports',
		['hash'] = `elegy`,
		['shop'] = 'luxury',
	},
	['elegy2'] = {
		['name'] = 'Elegy RH8',
		['brand'] = 'Annis',
		['model'] = 'elegy2',
		['price'] = 150000,
		['category'] = 'sports',
		['hash'] = `elegy2`,
		['shop'] = 'luxury',
	},
	['feltzer2'] = {
		['name'] = 'Feltzer',
		['brand'] = 'Benefactor',
		['model'] = 'feltzer2',
		['price'] = 97000,
		['category'] = 'sports',
		['hash'] = `feltzer2`,
		['shop'] = 'luxury',
	},
	['futo'] = {
		['name'] = 'Futo',
		['brand'] = 'Karin',
		['model'] = 'futo',
		['price'] = 17500,
		['category'] = 'coupes',
		['hash'] = `futo`,
		['shop'] = 'pdm',
	},
	['gb200'] = {
		['name'] = 'GB 200',
		['brand'] = 'Vapid',
		['model'] = 'gb200',
		['price'] = 140000,
		['category'] = 'sports',
		['hash'] = `gb200`,
		['shop'] = 'luxury',
	},
	['komoda'] = {
		['name'] = 'Komoda',
		['brand'] = 'Lampadati',
		['model'] = 'komoda',
		['price'] = 55000,
		['category'] = 'sports',
		['hash'] = `komoda`,
		['shop'] = 'luxury',
	},
	['italigto'] = {							--DLC
		['name'] = 'Itali GTO',
		['brand'] = 'Progen',
		['model'] = 'italigto',
		['price'] = 260000,
		['category'] = 'sports',
		['hash'] = `italigto`,
		['shop'] = 'luxury',
	},
	['jugular'] = {							--DLC
		['name'] = 'Jugular',
		['brand'] = 'Ocelot',
		['model'] = 'jugular',
		['price'] = 80000,
		['category'] = 'sports',
		['hash'] = `jugular`,
		['shop'] = 'luxury',
	},
	['jester'] = {
		['name'] = 'Jester',
		['brand'] = 'Dinka',
		['model'] = 'jester',
		['price'] = 132250,
		['category'] = 'sports',
		['hash'] = `jester`,
		['shop'] = 'luxury',
	},
	['jester3'] = {
		['name'] = 'Jester Classic',
		['brand'] = 'Dinka',
		['model'] = 'jester3',
		['price'] = 85000,
		['category'] = 'sports',
		['hash'] = `jester3`,
		['shop'] = 'luxury',
	},
	['kuruma'] = {
		['name'] = 'Kuruma',
		['brand'] = 'Karin',
		['model'] = 'kuruma',
		['price'] = 72000,
		['category'] = 'sports',
		['hash'] = `kuruma`,
		['shop'] = 'luxury',
	},
	['lynx'] = {
		['name'] = 'Lynx',
		['brand'] = 'Ocelot',
		['model'] = 'lynx',
		['price'] = 150000,
		['category'] = 'sports',
		['hash'] = `lynx`,
		['shop'] = 'luxury',
	},
	['massacro'] = {
		['name'] = 'Massacro',
		['brand'] = 'Dewbauchee',
		['model'] = 'massacro',
		['price'] = 110000,
		['category'] = 'sports',
		['hash'] = `massacro`,
		['shop'] = 'luxury',
	},
	['neon'] = {							--DLC
		['name'] = 'Neon',
		['brand'] = 'Pfister',
		['model'] = 'neon',
		['price'] = 220000,
		['category'] = 'sports',
		['hash'] = `neon`,
		['shop'] = 'luxury',
	},
	['ninef'] = {
		['name'] = '9F',
		['brand'] = 'Obey',
		['model'] = 'ninef',
		['price'] = 95000,
		['category'] = 'sports',
		['hash'] = `ninef`,
		['shop'] = 'luxury',
	},
	['ninef2'] = {
		['name'] = '9F Cabrio',
		['brand'] = 'Obey',
		['model'] = 'ninef2',
		['price'] = 105000,
		['category'] = 'sports',
		['hash'] = `ninef2`,
		['shop'] = 'luxury',
	},
	['pariah'] = {
		['name'] = 'Pariah',
		['brand'] = 'Ocelot',
		['model'] = 'pariah',
		['price'] = 90000,
		['category'] = 'sports',
		['hash'] = `pariah`,
		['shop'] = 'luxury',
	},
	['penumbra'] = {
		['name'] = 'Penumbra',
		['brand'] = 'Maibatsu',
		['model'] = 'penumbra',
		['price'] = 22000,
		['category'] = 'sports',
		['hash'] = `penumbra`,
		['shop'] = 'luxury',
	},
	['penumbra2'] = {
		['name'] = 'Penumbra FF',
		['brand'] = 'Maibatsu',
		['model'] = 'penumbra2',
		['price'] = 30000,
		['category'] = 'sports',
		['hash'] = `penumbra2`,
		['shop'] = 'luxury',
	},
	['rapidgt'] = {
		['name'] = 'Rapid GT',
		['brand'] = 'Dewbauchee',
		['model'] = 'rapidgt',
		['price'] = 86000,
		['category'] = 'sports',
		['hash'] = `rapidgt`,
		['shop'] = 'luxury',
	},
	['rapidgt2'] = {
		['name'] = 'Rapid GT Convertible',
		['brand'] = 'Dewbauchee',
		['model'] = 'rapidgt2',
		['price'] = 92000,
		['category'] = 'sports',
		['hash'] = `rapidgt2`,
		['shop'] = 'luxury',
	},
	['schafter2'] = {
		['name'] = 'Schafter',
		['brand'] = 'Benefactor',
		['model'] = 'schafter2',
		['price'] = 16000,
		['category'] = 'sedans',
		['hash'] = `schafter2`,
		['shop'] = 'pdm',
	},
	['schafter3'] = {
		['name'] = 'Schafter V12',
		['brand'] = 'Benefactor',
		['model'] = 'schafter3',
		['price'] = 35000,
		['category'] = 'sports',
		['hash'] = `schafter3`,
		['shop'] = 'luxury',
	},
	['schlagen'] = {							--DLC
		['name'] = 'Schlagen GT',
		['brand'] = 'Benefactor',
		['model'] = 'schlagen',
		['price'] = 160000,
		['category'] = 'sports',
		['hash'] = `schlagen`,
		['shop'] = 'luxury',
	},
	['schwarzer'] = {
		['name'] = 'Schwartzer',
		['brand'] = 'Benefactor',
		['model'] = 'schwarzer',
		['price'] = 47000,
		['category'] = 'sports',
		['hash'] = `schwarzer`,
		['shop'] = 'luxury',
	},
	['sentinel3'] = {
		['name'] = 'Sentinel Classic',
		['brand'] = 'Übermacht',
		['model'] = 'sentinel3',
		['price'] = 70000,
		['category'] = 'coupes',
		['hash'] = `sentinel3`,
		['shop'] = 'pdm',
	},
	['seven70'] = {
		['name'] = 'Seven-70',
		['brand'] = 'Dewbauchee',
		['model'] = 'seven70',
		['price'] = 140000,
		['category'] = 'sports',
		['hash'] = `seven70`,
		['shop'] = 'luxury',
	},
	['specter'] = {
		['name'] = 'Specter',
		['brand'] = 'Dewbauchee',
		['model'] = 'specter',
		['price'] = 160000,
		['category'] = 'sports',
		['hash'] = `specter`,
		['shop'] = 'luxury',
	},
	['sugoi'] = {
		['name'] = 'Sugoi',
		['brand'] = 'Dinka',
		['model'] = 'sugoi',
		['price'] = 85000,
		['category'] = 'sports',
		['hash'] = `sugoi`,
		['shop'] = 'luxury',
	},
	['sultan'] = {
		['name'] = 'Sultan',
		['brand'] = 'Karin',
		['model'] = 'sultan',
		['price'] = 50000,
		['category'] = 'sports',
		['hash'] = `sultan`,
		['shop'] = 'luxury',
	},
	['sultan2'] = {
		['name'] = 'Sultan Custom',
		['brand'] = 'Karin',
		['model'] = 'sultan2',
		['price'] = 55000,
		['category'] = 'sports',
		['hash'] = `sultan2`,
		['shop'] = 'luxury',
	},
	['surano'] = {
		['name'] = 'Surano',
		['brand'] = ' Benefactor',
		['model'] = 'surano',
		['price'] = 80000,
		['category'] = 'sports',
		['hash'] = `surano`,
		['shop'] = 'luxury',
	},
	['tropos'] = {
		['name'] = 'Tropos Rallye',
		['brand'] = 'Lampadati',
		['model'] = 'tropos',
		['price'] = 65000,
		['category'] = 'sports',
		['hash'] = `tropos`,
		['shop'] = 'luxury',
	},
	['vstr'] = {
		['name'] = 'V-STR',
		['brand'] = 'Albany',
		['model'] = 'vstr',
		['price'] = 80000,
		['category'] = 'sports',
		['hash'] = `vstr`,
		['shop'] = 'luxury',
	},
	['zr350'] = {							--DLC +set sv_enforceGameBuild 2372
		['name'] = 'ZR350',
		['brand'] = 'Annis',
		['model'] = 'zr350',
		['price'] = 38000,
		['category'] = 'sports',
		['hash'] = `zr350`,
		['shop'] = 'luxury',
	},
	['calico'] = {							--DLC +set sv_enforceGameBuild 2372
		['name'] = 'Calico GTF',
		['brand'] = 'Karin',
		['model'] = 'calico',
		['price'] = 39000,
		['category'] = 'sports',
		['hash'] = `calico`,
		['shop'] = 'luxury',
	},
	['futo2'] = {							--DLC +set sv_enforceGameBuild 2372
		['name'] = 'Futo GTX',
		['brand'] = 'Karin',
		['model'] = 'futo2',
		['price'] = 39000,
		['category'] = 'sports',
		['hash'] = `futo2`,
		['shop'] = 'luxury',
	},
	['euros'] = {							--DLC +set sv_enforceGameBuild 2372
		['name'] = 'Euros',
		['brand'] = 'Annis',
		['model'] = 'euros',
		['price'] = 80000,
		['category'] = 'sports',
		['hash'] = `euros`,
		['shop'] = 'luxury',
	},
	['remus'] = {							--DLC +set sv_enforceGameBuild 2372
		['name'] = 'Remus',
		['brand'] = 'Annis',
		['model'] = 'remus',
		['price'] = 48000,
		['category'] = 'sports',
		['hash'] = `remus`,
		['shop'] = 'luxury',
	},
	['comet6'] = {							--DLC +set sv_enforceGameBuild 2372
		['name'] = 'Comet S2',
		['brand'] = 'Pfister',
		['model'] = 'comet6',
		['price'] = 230000,
		['category'] = 'sports',
		['hash'] = `comet6`,
		['shop'] = 'luxury',
	},
	['growler'] = {							--DLC +set sv_enforceGameBuild 2372
		['name'] = 'Growler',
		['brand'] = 'Pfister',
		['model'] = 'growler',
		['price'] = 205000,
		['category'] = 'sports',
		['hash'] = `growler`,
		['shop'] = 'luxury',
	},
	['vectre'] = {							--DLC +set sv_enforceGameBuild 2372
		['name'] = 'Emperor Vectre',
		['brand'] = 'Emperor',
		['model'] = 'vectre',
		['price'] = 80000,
		['category'] = 'sports',
		['hash'] = `vectre`,
		['shop'] = 'luxury',
	},
	['cypher'] = {							--DLC +set sv_enforceGameBuild 2372
		['name'] = 'Cypher',
		['brand'] = 'Ubermacht',
		['model'] = 'cypher',
		['price'] = 155000,
		['category'] = 'sports',
		['hash'] = `cypher`,
		['shop'] = 'luxury',
	},
	['sultan3'] = {							--DLC +set sv_enforceGameBuild 2372
		['name'] = 'Sultan Classic Custom',
		['brand'] = 'Karin',
		['model'] = 'sultan3',
		['price'] = 56000,
		['category'] = 'sports',
		['hash'] = `sultan3`,
		['shop'] = 'luxury',
	},
	['rt3000'] = {							--DLC +set sv_enforceGameBuild 2372
		['name'] = 'RT3000',
		['brand'] = 'Dinka',
		['model'] = 'rt3000',
		['price'] = 65000,
		['category'] = 'sports',
		['hash'] = `rt3000`,
		['shop'] = 'luxury',
	},
	--- Sports Classic
	['ardent'] = {
		['name'] = 'Ardent',
		['brand'] = 'Ocelot',
		['model'] = 'ardent',
		['price'] = 30000,
		['category'] = 'sportsclassics',
		['hash'] = `ardent`,
		['shop'] = 'pdm',
	},
	['btype'] = {              --meme car that goes pretty fast
		['name'] = 'Roosevelt',
		['brand'] = 'Albany',
		['model'] = 'btype',
		['price'] = 75000,
		['category'] = 'sportsclassics',
		['hash'] = `btype`,
		['shop'] = 'pdm',
	},
	['btype3'] = {
		['name'] = 'Roosevelt Valor',
		['brand'] = 'Albany',
		['model'] = 'btype3',
		['price'] = 63000,
		['category'] = 'sportsclassics',
		['hash'] = `btype3`,
		['shop'] = 'pdm',
	},
	['casco'] = {
		['name'] = 'Casco',
		['brand'] = 'Lampadati',
		['model'] = 'casco',
		['price'] = 100000,
		['category'] = 'sportsclassics',
		['hash'] = `casco`,
		['shop'] = 'pdm',
	},
	['cheetah2'] = {
		['name'] = 'Cheetah Classic',
		['brand'] = 'Grotti',
		['model'] = 'cheetah2',
		['price'] = 195000,
		['category'] = 'sports',
		['hash'] = `cheetah2`,
		['shop'] = 'luxury',
	},
	['feltzer3'] = {							--DLC
		['name'] = 'Stirling GT',
		['brand'] = 'Benefactor',
		['model'] = 'feltzer3',
		['price'] = 115000,
		['category'] = 'sportsclassics',
		['hash'] = `feltzer3`,
		['shop'] = 'pdm',
	},
	['gt500'] = {
		['name'] = 'GT500',
		['brand'] = 'Grotti',
		['model'] = 'gt500',
		['price'] = 130000,
		['category'] = 'sportsclassics',
		['hash'] = `gt500`,
		['shop'] = 'pdm',
	},
	['infernus2'] = {
		['name'] = 'Infernus Classic',
		['brand'] = 'Pegassi',
		['model'] = 'infernus2',
		['price'] = 245000,
		['category'] = 'sportsclassics',
		['hash'] = `infernus2`,
		['shop'] = 'pdm',
	},
	['mamba'] = {
		['name'] = 'Mamba',
		['brand'] = 'Declasse',
		['model'] = 'mamba',
		['price'] = 140000,
		['category'] = 'sportsclassics',
		['hash'] = `mamba`,
		['shop'] = 'pdm',
	},
	['manana'] = {
		['name'] = 'Manana',
		['brand'] = 'Albany',
		['model'] = 'manana',
		['price'] = 12800,
		['category'] = 'muscle',
		['hash'] = `manana`,
		['shop'] = 'pdm',
	},
	['michelli'] = {
		['name'] = 'Michelli GT',
		['brand'] = 'Lampadati',
		['model'] = 'michelli',
		['price'] = 30000,
		['category'] = 'sportsclassics',
		['hash'] = `michelli`,
		['shop'] = 'pdm',
	},
	['monroe'] = {
		['name'] = 'Monroe',
		['brand'] = 'Pegassi',
		['model'] = 'monroe',
		['price'] = 115000,
		['category'] = 'sportsclassics',
		['hash'] = `monroe`,
		['shop'] = 'pdm',
	},
	['nebula'] = {							--DLC
		['name'] = 'Nebula',
		['brand'] = 'Vulcar',
		['model'] = 'nebula',
		['price'] = 22000,
		['category'] = 'sportsclassics',
		['hash'] = `nebula`,
		['shop'] = 'pdm',
	},
	['rapidgt3'] = {
		['name'] = 'Rapid GT',
		['brand'] = 'Dewbauchee',
		['model'] = 'rapidgt3',
		['price'] = 90000,
		['category'] = 'sportsclassics',
		['hash'] = `rapidgt3`,
		['shop'] = 'pdm',
	},
	['retinue'] = {
		['name'] = 'Retinue',
		['brand'] = 'Vapid',
		['model'] = 'retinue',
		['price'] = 32000,
		['category'] = 'sportsclassics',
		['hash'] = `retinue`,
		['shop'] = 'pdm',
	},
	['retinue2'] = {
		['name'] = 'Retinue MKII',
		['brand'] = 'Vapid',
		['model'] = 'retinue2',
		['price'] = 38000,
		['category'] = 'sportsclassics',
		['hash'] = `retinue2`,
		['shop'] = 'pdm',
	},
	['savestra'] = {
		['name'] = 'Savestra',
		['brand'] = 'Annis',
		['model'] = 'savestra',
		['price'] = 67000,
		['category'] = 'sportsclassics',
		['hash'] = `savestra`,
		['shop'] = 'pdm',
	},
	['torero'] = {
		['name'] = 'Torero',
		['brand'] = 'Pegassi',
		['model'] = 'torero',
		['price'] = 84000,
		['category'] = 'sportsclassics',
		['hash'] = `torero`,
		['shop'] = 'pdm',
	},
	['tornado'] = {
		['name'] = 'Tornado',
		['brand'] = 'Declasse',
		['model'] = 'tornado',
		['price'] = 21000,
		['category'] = 'sportsclassics',
		['hash'] = `tornado`,
		['shop'] = 'pdm',
	},
	['turismo2'] = {
		['name'] = 'Turismo Classic',
		['brand'] = 'Grotti',
		['model'] = 'turismo2',
		['price'] = 170000,
		['category'] = 'sportsclassics',
		['hash'] = `turismo2`,
		['shop'] = 'pdm',
	},
	['viseris'] = {
		['name'] = 'Viseris',
		['brand'] = 'Lampadati',
		['model'] = 'viseris',
		['price'] = 210000,
		['category'] = 'sportsclassics',
		['hash'] = `viseris`,
		['shop'] = 'pdm',
	},
	['z190'] = {
		['name'] = '190Z',
		['brand'] = 'Karin',
		['model'] = 'z190',
		['price'] = 78000,
		['category'] = 'sportsclassics',
		['hash'] = `z190`,
		['shop'] = 'pdm',
	},
	['zion3'] = {							--DLC
		['name'] = 'Zion Classic',
		['brand'] = 'Übermacht',
		['model'] = 'zion3',
		['price'] = 45000,
		['category'] = 'sportsclassics',
		['hash'] = `zion3`,
		['shop'] = 'pdm',
	},
	['cheburek'] = {
		['name'] = 'Cheburek',
		['brand'] = 'Rune',
		['model'] = 'cheburek',
		['price'] = 7000,
		['category'] = 'sportsclassics',
		['hash'] = `cheburek`,
		['shop'] = 'pdm',
	},
	--- Super
	['adder'] = {
		['name'] = 'Adder',
		['brand'] = 'Truffade',
		['model'] = 'adder',
		['price'] = 280000,
		['category'] = 'super',
		['hash'] = `adder`,
		['shop'] = 'luxury',
	},
	['banshee2'] = {
		['name'] = 'Banshee 900R',
		['brand'] = 'Bravado',
		['model'] = 'banshee2',
		['price'] = 120000,
		['category'] = 'super',
		['hash'] = `banshee2`,
		['shop'] = 'luxury',
	},
	['bullet'] = {
		['name'] = 'Bullet',
		['brand'] = 'Vapid',
		['model'] = 'bullet',
		['price'] = 120000,
		['category'] = 'super',
		['hash'] = `bullet`,
		['shop'] = 'luxury',
	},
	['cyclone'] = {         --might be too overpowered
		['name'] = 'Cyclone',
		['brand'] = 'Coil',
		['model'] = 'cyclone',
		['price'] = 300000,
		['category'] = 'super',
		['hash'] = `cyclone`,
		['shop'] = 'luxury',
	},
	['entity2'] = {
		['name'] = 'Entity XXR',
		['brand'] = 'Överflöd',
		['model'] = 'entity2',
		['price'] = 164000,
		['category'] = 'super',
		['hash'] = `entity2`,
		['shop'] = 'luxury',
	},
	['entityxf'] = {
		['name'] = 'Entity XF',
		['brand'] = 'Överflöd',
		['model'] = 'entityxf',
		['price'] = 180000,
		['category'] = 'super',
		['hash'] = `entityxf`,
		['shop'] = 'luxury',
	},
	['fmj'] = {
		['name'] = 'FMJ',
		['brand'] = 'Vapid',
		['model'] = 'fmj',
		['price'] = 125000,
		['category'] = 'super',
		['hash'] = `fmj`,
		['shop'] = 'luxury',
	},
	['furia'] = {
		['name'] = 'Furia',
		['brand'] = 'Grotti',
		['model'] = 'furia',
		['price'] = 230000,
		['category'] = 'super',
		['hash'] = `furia`,
		['shop'] = 'luxury',
	},
	['infernus'] = {
		['name'] = 'Infernus',
		['brand'] = 'Pegassi',
		['model'] = 'infernus',
		['price'] = 235000,
		['category'] = 'super',
		['hash'] = `infernus`,
		['shop'] = 'luxury',
	},
	['italigtb'] = {
		['name'] = 'Itali GTB',
		['brand'] = 'Progen',
		['model'] = 'italigtb',
		['price'] = 170000,
		['category'] = 'super',
		['hash'] = `italigtb`,
		['shop'] = 'luxury',
	},
	['italigtb2'] = {
		['name'] = 'Itali GTB',
		['brand'] = 'Progen',
		['model'] = 'italigtb2',
		['price'] = 250000,
		['category'] = 'super',
		['hash'] = `italigtb2`,
		['shop'] = 'luxury',
	},
	['krieger'] = {							--DLC
		['name'] = 'Krieger',
		['brand'] = 'Benefactor',
		['model'] = 'krieger',
		['price'] = 222000,
		['category'] = 'super',
		['hash'] = `krieger`,
		['shop'] = 'luxury',
	},
	['nero'] = {
		['name'] = 'Nero',
		['brand'] = 'Truffade',
		['model'] = 'nero',
		['price'] = 200000,
		['category'] = 'super',
		['hash'] = `nero`,
		['shop'] = 'luxury',
	},
	['nero2'] = {
		['name'] = 'Nero Custom',
		['brand'] = 'Truffade',
		['model'] = 'nero2',
		['price'] = 260000,
		['category'] = 'super',
		['hash'] = `nero2`,
		['shop'] = 'luxury',
	},
	['osiris'] = {
		['name'] = 'Osiris',
		['brand'] = 'Pegassi',
		['model'] = 'osiris',
		['price'] = 220000,
		['category'] = 'super',
		['hash'] = `osiris`,
		['shop'] = 'luxury',
	},
	['reaper'] = {
		['name'] = 'Reaper',
		['brand'] = 'Pegassi',
		['model'] = 'reaper',
		['price'] = 100000,
		['category'] = 'super',
		['hash'] = `reaper`,
		['shop'] = 'luxury',
	},
	['sultanrs'] = {
		['name'] = 'Sultan RS',
		['brand'] = 'Karin',
		['model'] = 'sultanrs',
		['price'] = 76500,
		['category'] = 'sports',
		['hash'] = `sultanrs`,
		['shop'] = 'luxury',
	},
	['t20'] = {
		['name'] = 'T20',
		['brand'] = 'Progen',
		['model'] = 't20',
		['price'] = 1650000,
		['category'] = 'super',
		['hash'] = `t20`,
		['shop'] = 'luxury',
	},
	['tempesta'] = {
		['name'] = 'Tempesta',
		['brand'] = 'Pegassi',
		['model'] = 'tempesta',
		['price'] = 120000,
		['category'] = 'super',
		['hash'] = `tempesta`,
		['shop'] = 'luxury',
	},
	['thrax'] = {							--DLC
		['name'] = 'Thrax',
		['brand'] = 'Truffade',
		['model'] = 'thrax',
		['price'] = 180000,
		['category'] = 'super',
		['hash'] = `thrax`,
		['shop'] = 'luxury',
	},
	['turismor'] = {
		['name'] = 'Turismo R',
		['brand'] = 'Grotti',
		['model'] = 'turismor',
		['price'] = 140000,
		['category'] = 'super',
		['hash'] = `turismor`,
		['shop'] = 'luxury',
	},
	['vacca'] = {
		['name'] = 'Vacca',
		['brand'] = 'Pegassi',
		['model'] = 'vacca',
		['price'] = 105000,
		['category'] = 'super',
		['hash'] = `vacca`,
		['shop'] = 'luxury',
	},
	['voltic'] = {
		['name'] = 'Voltic',
		['brand'] = 'Coil',
		['model'] = 'voltic',
		['price'] = 120000,
		['category'] = 'super',
		['hash'] = `voltic`,
		['shop'] = 'luxury',
	},
	['zentorno'] = {
		['name'] = 'Zentorno',
		['brand'] = 'Pegassi',
		['model'] = 'zentorno',
		['price'] = 340000,
		['category'] = 'super',
		['hash'] = `zentorno`,
		['shop'] = 'luxury',
	},
	-- Vans
	['bison'] = {
		['name'] = 'Bison',
		['brand'] = 'Bravado',
		['model'] = 'bison',
		['price'] = 18000,
		['category'] = 'vans',
		['hash'] = `bison`,
		['shop'] = 'pdm',
	},
	['bobcatxl'] = {
		['name'] = 'Bobcat XL Open',
		['brand'] = 'Vapid',
		['model'] = 'bobcatxl',
		['price'] = 13500,
		['category'] = 'vans',
		['hash'] = `bobcatxl`,
		['shop'] = 'pdm',
	},
	['burrito3'] = {
		['name'] = 'Burrito',
		['brand'] = 'Declasse',
		['model'] = 'burrito3',
		['price'] = 4000,
		['category'] = 'vans',
		['hash'] = `burrito3`,
		['shop'] = 'pdm',
	},
	['gburrito2'] = {
		['name'] = 'Burrito Custom',
		['brand'] = 'Declasse',
		['model'] = 'gburrito2',
		['price'] = 11500,
		['category'] = 'vans',
		['hash'] = `gburrito2`,
		['shop'] = 'pdm',
	},
	['rumpo'] = {
		['name'] = 'Rumpo',
		['brand'] = 'Bravado',
		['model'] = 'rumpo',
		['price'] = 9000,
		['category'] = 'vans',
		['hash'] = `rumpo`,
		['shop'] = 'pdm',
	},
	['journey'] = {
		['name'] = 'Journey',
		['brand'] = 'Zirconium',
		['model'] = 'journey',
		['price'] = 6500,
		['category'] = 'vans',
		['hash'] = `journey`,
		['shop'] = 'pdm',
	},
	['minivan'] = {
		['name'] = 'Minivan',
		['brand'] = 'Vapid',
		['model'] = 'minivan',
		['price'] = 7000,
		['category'] = 'vans',
		['hash'] = `minivan`,
		['shop'] = 'pdm',
	},
	['minivan2'] = {
		['name'] = 'Minivan Custom',
		['brand'] = 'Vapid',
		['model'] = 'minivan2',
		['price'] = 10000,
		['category'] = 'vans',
		['hash'] = `minivan2`,
		['shop'] = 'pdm',
	},
	['paradise'] = {
		['name'] = 'Paradise',
		['brand'] = 'Bravado',
		['model'] = 'paradise',
		['price'] = 9000,
		['category'] = 'vans',
		['hash'] = `paradise`,
		['shop'] = 'pdm',
	},
	['rumpo3'] = {
		['name'] = 'Rumpo Custom',
		['brand'] = 'Bravado',
		['model'] = 'rumpo3',
		['price'] = 19500,
		['category'] = 'vans',
		['hash'] = `rumpo3`,
		['shop'] = 'pdm',
	},
	['speedo'] = {
		['name'] = 'Speedo',
		['brand'] = 'Vapid',
		['model'] = 'speedo',
		['price'] = 10000,
		['category'] = 'vans',
		['hash'] = `speedo`,
		['shop'] = 'pdm',
	},
	['speedo4'] = {
		['name'] = 'Speedo Custom',
		['brand'] = 'Vapid',
		['model'] = 'speedo4',
		['price'] = 15000,
		['category'] = 'vans',
		['hash'] = `speedo4`,
		['shop'] = 'pdm',
	},
	['surfer'] = {
		['name'] = 'Surfer',
		['brand'] = 'BF',
		['model'] = 'surfer',
		['price'] = 9000,
		['category'] = 'vans',
		['hash'] = `surfer`,
		['shop'] = 'pdm',
	},
	['youga'] = {
		['name'] = 'Youga',
		['brand'] = 'Bravado',
		['model'] = 'youga',
		['price'] = 8000,
		['category'] = 'vans',
		['hash'] = `youga`,
		['shop'] = 'pdm',
	},
	['youga2'] = {
		['name'] = 'Youga Classic',
		['brand'] = 'Bravado',
		['model'] = 'youga2',
		['price'] = 14500,
		['category'] = 'vans',
		['hash'] = `youga2`,
		['shop'] = 'pdm',
	},
	['mule5'] = { 	 	--DLC +set sv_enforceGameBuild 2545
		['name'] = 'Mule',
		['brand'] = 'Box Truck',
		['model'] = 'mule5',
		['price'] = 221000,
		['category'] = 'vans',
		['hash'] = `mule5`,
		['shop'] = 'pdm',
	},
	-- Utility
	['sadler'] = {
		['name'] = 'Sadler',
		['brand'] = 'Vapid',
		['model'] = 'sadler',
		['price'] = 20000,
		['category'] = 'offroad',
		['hash'] = `sadler`,
		['shop'] = 'pdm',
	},
		-- Boats
	['squalo'] = {
		['name'] = 'Squalo',
		['brand'] = 'Shitzu',
		['model'] = 'squalo',
		['price'] = 40000,
		['category'] = 'boats',
		['hash'] = `squalo`,
		['shop'] = 'boats',
	},
	['marquis'] = {
		['name'] = 'Marquis',
		['brand'] = 'Dinka',
		['model'] = 'marquis',
		['price'] = 40000,
		['category'] = 'boats',
		['hash'] = `marquis`,
		['shop'] = 'boats',
	},
	['seashark'] = {
		['name'] = 'Seashark',
		['brand'] = 'Speedophile',
		['model'] = 'seashark',
		['price'] = 40000,
		['category'] = 'boats',
		['hash'] = `seashark`,
		['shop'] = 'boats',
	},
	['seashark2'] = {
		['name'] = 'Seashark',
		['brand'] = 'Speedophile',
		['model'] = 'seashark2',
		['price'] = 40000,
		['category'] = 'boats',
		['hash'] = `seashark2`,
		['shop'] = 'boats',
	},
	['seashark3'] = {
		['name'] = 'Seashark',
		['brand'] = 'Speedophile',
		['model'] = 'seashark3',
		['price'] = 40000,
		['category'] = 'boats',
		['hash'] = `seashark3`,
		['shop'] = 'boats',
	},
	['jetmax'] = {
		['name'] = 'Shitzu',
		['brand'] = 'Jetmax',
		['model'] = 'jetmax',
		['price'] = 40000,
		['category'] = 'boats',
		['hash'] = `jetmax`,
		['shop'] = 'boats',
	},
	['tropic'] = {
		['name'] = 'Shitzu',
		['brand'] = 'Tropic',
		['model'] = 'tropic',
		['price'] = 40000,
		['category'] = 'boats',
		['hash'] = `tropic`,
		['shop'] = 'boats',
	},
	['tropic2'] = {
		['name'] = 'Shitzu',
		['brand'] = 'Tropic',
		['model'] = 'tropic2',
		['price'] = 40000,
		['category'] = 'boats',
		['hash'] = `tropic2`,
		['shop'] = 'boats',
	},
	['dinghy'] = {
		['name'] = 'Nagasaki',
		['brand'] = 'Dinghy',
		['model'] = 'dinghy',
		['price'] = 40000,
		['category'] = 'boats',
		['hash'] = `dinghy`,
		['shop'] = 'boats',
	},
	['dinghy2'] = {
		['name'] = 'Nagasaki',
		['brand'] = 'Dinghy',
		['model'] = 'dinghy2',
		['price'] = 40000,
		['category'] = 'boats',
		['hash'] = `dinghy2`,
		['shop'] = 'boats',
	},
	['dinghy3'] = {
		['name'] = 'Nagasaki',
		['brand'] = 'Dinghy',
		['model'] = 'dinghy3',
		['price'] = 40000,
		['category'] = 'boats',
		['hash'] = `dinghy3`,
		['shop'] = 'boats',
	},
	['dinghy4'] = {
		['name'] = 'Nagasaki',
		['brand'] = 'Dinghy',
		['model'] = 'dinghy4',
		['price'] = 40000,
		['category'] = 'boats',
		['hash'] = `dinghy4`,
		['shop'] = 'boats',
	},
	['suntrap'] = {
		['name'] = 'Shitzu',
		['brand'] = 'Suntrap',
		['model'] = 'suntrap',
		['price'] = 40000,
		['category'] = 'boats',
		['hash'] = `suntrap`,
		['shop'] = 'boats',
	},
	['speeder'] = {
		['name'] = 'Speeder',
		['brand'] = 'Pegassi',
		['model'] = 'speeder',
		['price'] = 40000,
		['category'] = 'boats',
		['hash'] = `speeder`,
		['shop'] = 'boats',
	},
	['speeder2'] = {
		['name'] = 'Speeder',
		['brand'] = 'Pegassi',
		['model'] = 'speeder2',
		['price'] = 40000,
		['category'] = 'boats',
		['hash'] = `speeder2`,
		['shop'] = 'boats',
	},
	['longfin'] = {
		['name'] = 'Longfin',
		['brand'] = 'Shitzu',
		['model'] = 'longfin',
		['price'] = 40000,
		['category'] = 'boats',
		['hash'] = `longfin`,
		['shop'] = 'boats',
	},
	['toro'] = {
		['name'] = 'Toro',
		['brand'] = 'Lampadati',
		['model'] = 'toro',
		['price'] = 40000,
		['category'] = 'boats',
		['hash'] = `toro`,
		['shop'] = 'boats',
	},
	['toro2'] = {
		['name'] = 'Toro',
		['brand'] = 'Lampadati',
		['model'] = 'toro2',
		['price'] = 40000,
		['category'] = 'boats',
		['hash'] = `toro2`,
		['shop'] = 'boats',
	},
	-- helicopters
	['frogger'] = {
		['name'] = 'Frogger',
		['brand'] = 'Unknown',
		['model'] = 'frogger',
		['price'] = 52000,
		['category'] = 'helicopters',
		['hash'] = `frogger`,
		['shop'] = 'air',
	},
	['frogger2'] = {
		['name'] = 'Frogger',
		['brand'] = 'Unknown',
		['model'] = 'frogger2',
		['price'] = 52000,
		['category'] = 'helicopters',
		['hash'] = `frogger2`,
		--['shop'] = 'air',
	},
	['maverick'] = {
		['name'] = 'Maverick',
		['brand'] = 'Unknown',
		['model'] = 'maverick',
		['price'] = 52000,
		['category'] = 'helicopters',
		['hash'] = `maverick`,
		['shop'] = 'air',
	},
	['swift'] = {
		['name'] = 'Swift',
		['brand'] = 'Buckingham',
		['model'] = 'swift',
		['price'] = 52000,
		['category'] = 'helicopters',
		['hash'] = `swift`,
		['shop'] = 'air',
	},
	['seasparrow'] = {
		['name'] = 'Sea Sparrow',
		['brand'] = 'Unknown',
		['model'] = 'seasparrow',
		['price'] = 52000,
		['category'] = 'helicopters',
		['hash'] = `seasparrow`,
		['shop'] = 'air',
	},
	['supervolito'] = {
		['name'] = 'SuperVolito',
		['brand'] = 'Buckingham',
		['model'] = 'supervolito',
		['price'] = 52000,
		['category'] = 'helicopters',
		['hash'] = `supervolito`,
		['shop'] = 'air',
	},
	['supervolito2'] = {
		['name'] = 'SuperVolito Carbon',
		['brand'] = 'Buckingham',
		['model'] = 'supervolito2',
		['price'] = 52000,
		['category'] = 'helicopters',
		['hash'] = `supervolito2`,
		['shop'] = 'air',
	},
	--[[
	['volatus'] = {
		['name'] = 'Volatus',
		['brand'] = 'Buckingham',
		['model'] = 'volatus',
		['price'] = 52000,
		['category'] = 'helicopters',
		['hash'] = `volatus`,
		['shop'] = 'air',
	},
	]]--
	-- Planes
	['mammatus'] = {
		['name'] = 'Mammatus',
		['brand'] = 'Unknown',
		['model'] = 'mammatus',
		['price'] = 45000,
		['category'] = 'planes',
		['hash'] = `mammatus`,
		['shop'] = 'air',
	},
	['velum2'] = {
		['name'] = 'Velum',
		['brand'] = 'Unknown',
		['model'] = 'velum2',
		['price'] = 215000,
		['category'] = 'planes',
		['hash'] = `velum2`,
		['shop'] = 'air',
	},
	['vestra'] = {
		['name'] = 'Vestra',
		['brand'] = 'Buckingham',
		['model'] = 'vestra',
		['price'] = 45000,
		['category'] = 'planes',
		['hash'] = `vestra`,
		['shop'] = 'air',
	},
	['dodo'] = {
		['name'] = 'Dodo',
		['brand'] = 'Mammoth',
		['model'] = 'dodo',
		['price'] = 85000,
		['category'] = 'planes',
		['hash'] = `dodo`,
		['shop'] = 'air',
	},
	['nimbus'] = {
		['name'] = 'Nimbus',
		['brand'] = 'Buckingham',
		['model'] = 'nimbus',
		['price'] = 1700000,
		['category'] = 'planes',
		['hash'] = `nimbus`,
		['shop'] = 'air',
	},

	-- LUAP VEHICELS --

	['chr20'] = {
        ['name'] = '2020 Hellcat',
        ['brand'] = 'Dodge',
        ['model'] = 'chr20',
        ['price'] = 1000000,
        ['category'] = 'muscle',
        ['hash'] = `chr20`,
        ['shop'] = 'luap',
    },
	['redeye'] = {
        ['name'] = 'Redeye',
        ['brand'] = 'Dodge',
        ['model'] = 'redeye',
        ['price'] = 1000000,
        ['category'] = 'muscle',
        ['hash'] = `redeye`,
        ['shop'] = 'luap',
    },
	['bdragon'] = {
        ['name'] = 'Bentley Dragon',
        ['brand'] = 'Bentley',
        ['model'] = 'bdragonblue',
        ['price'] = 1000000,
        ['category'] = 'sports',
        ['hash'] = `bdragonblue`,
        ['shop'] = 'luap',
    },
	['m3e36'] = {
        ['name'] = 'M3 E36',
        ['brand'] = 'BMW',
        ['model'] = 'm3e36',
        ['price'] = 1000000,
        ['category'] = 'sports',
        ['hash'] = `m3e36`,
        ['shop'] = 'luap',
    },
	['manssupersnake'] = {
        ['name'] = 'Supersnake',
        ['brand'] = 'Ford',
        ['model'] = 'manssupersnake',
        ['price'] = 1000000,
        ['category'] = 'muscle',
        ['hash'] = `manssupersnake`,
        ['shop'] = 'luap',
    },

	----------------------------------------
	
	-- luxury shop --
	['amgone'] = {
        ['name'] = 'AMG One',
        ['brand'] = 'Mercedes',
        ['model'] = 'amgone',
        ['price'] = 120000,
        ['category'] = 'super',
        ['hash'] = `amgone`,
        ['shop'] = 'luxury',
    },
	['rmodlfa'] = {
        ['name'] = 'Lexus LFA',
        ['brand'] = 'Lexus',
        ['model'] = 'rmodlfa',
        ['price'] = 120000,
        ['category'] = 'super',
        ['hash'] = `rmodlfa`,
        ['shop'] = 'luxury',
    },
	['ghoulcharger'] = {
        ['name'] = 'Ghoul Charger',
        ['brand'] = 'Dodge',
        ['model'] = 'ghoulcharger',
        ['price'] = 120000,
        ['category'] = 'muscle',
        ['hash'] = `ghoulcharger`,
        ['shop'] = 'luxury',
    },

	----------------------------------------
	
	-- tuner shop --

	['z32midnight'] = {
        ['name'] = 'Z32 Midnight',
        ['brand'] = 'Nissan',
        ['model'] = 'z32midnight',
        ['price'] = 120000,
        ['category'] = 'tuner',
        ['hash'] = `z32midnight`,
        ['shop'] = 'tuner',
    },
	['subisti08'] = {
        ['name'] = '2008 STI',
        ['brand'] = 'Subaru',
        ['model'] = 'subisti08',
        ['price'] = 120000,
        ['category'] = 'tuner',
        ['hash'] = `subisti08`,
        ['shop'] = 'tuner',
    },
	['subwrx'] = {
        ['name'] = 'WRX',
        ['brand'] = 'Subaru',
        ['model'] = 'subwrx',
        ['price'] = 120000,
        ['category'] = 'tuner',
        ['hash'] = `subwrx`,
        ['shop'] = 'tuner',
    },
	['subwrx'] = {
        ['name'] = 'WRX',
        ['brand'] = 'Subaru',
        ['model'] = 'subwrx',
        ['price'] = 120000,
        ['category'] = 'tuner',
        ['hash'] = `subwrx`,
        ['shop'] = 'tuner',
    },
	['ttrs'] = {
        ['name'] = 'TT RS',
        ['brand'] = 'Audi',
        ['model'] = 'ttrs',
        ['price'] = 120000,
        ['category'] = 'tuner',
        ['hash'] = `ttrs`,
        ['shop'] = 'tuner',
    },
	['topsecretsupra'] = {
        ['name'] = 'Top Secret Supra',
        ['brand'] = 'Toyota',
        ['model'] = 'topsecretsupra',
        ['price'] = 120000,
        ['category'] = 'tuner',
        ['hash'] = `topsecretsupra`,
        ['shop'] = 'tuner',
    },
	['tbkr33'] = {
        ['name'] = 'Top Secret Supra',
        ['brand'] = 'Nissan',
        ['model'] = 'tbkr33',
        ['price'] = 120000,
        ['category'] = 'tuner',
        ['hash'] = `tbkr33`,
        ['shop'] = 'tuner',
    },
	['a80'] = {
        ['name'] = 'Supra MK4',
        ['brand'] = 'Toyota',
        ['model'] = 'a80',
        ['price'] = 120000,
        ['category'] = 'tuner',
        ['hash'] = `a80`,
        ['shop'] = 'tuner',
    },
	['mz3'] = {
        ['name'] = 'Speed 3',
        ['brand'] = 'Mazda',
        ['model'] = 'mz3',
        ['price'] = 120000,
        ['category'] = 'tuner',
        ['hash'] = `mz3`,
        ['shop'] = 'tuner',
    },
	['lexsc300'] = {
        ['name'] = 'Speed 3',
        ['brand'] = 'Lexus',
        ['model'] = 'lexsc300',
        ['price'] = 120000,
        ['category'] = 'tuner',
        ['hash'] = `lexsc300`,
        ['shop'] = 'tuner',
    },
	['ap2'] = {
        ['name'] = 'S2000',
        ['brand'] = 'Honda',
        ['model'] = 'ap2',
        ['price'] = 120000,
        ['category'] = 'tuner',
        ['hash'] = `ap2`,
        ['shop'] = 'tuner',
    },
	['devilz'] = {
        ['name'] = 'Fairlady Z',
        ['brand'] = 'Nissan',
        ['model'] = 'devilz',
        ['price'] = 120000,
        ['category'] = 'tuner',
        ['hash'] = `devilz`,
        ['shop'] = 'tuner',
    },
	['s15yokoi'] = {
        ['name'] = 'S15 Yokoi',
        ['brand'] = 'Nissan',
        ['model'] = 's15yokoi',
        ['price'] = 120000,
        ['category'] = 'tuner',
        ['hash'] = `s15yokoi`,
        ['shop'] = 'tuner',
    },
	['s15worthouse'] = {
        ['name'] = 'S15 Worthouse',
        ['brand'] = 'Nissan',
        ['model'] = 's15worthouse',
        ['price'] = 120000,
        ['category'] = 'tuner',
        ['hash'] = `s15worthouse`,
        ['shop'] = 'tuner',
    },
	['s15lbwk'] = {
        ['name'] = 'S15 Liberty Walk',
        ['brand'] = 'Nissan',
        ['model'] = 's15lbwk',
        ['price'] = 120000,
        ['category'] = 'tuner',
        ['hash'] = `s15lbwk`,
        ['shop'] = 'tuner',
    },
	['s14boss'] = {
        ['name'] = 'S14 Boss',
        ['brand'] = 'Nissan',
        ['model'] = 's14boss',
        ['price'] = 120000,
        ['category'] = 'tuner',
        ['hash'] = `s14boss`,
        ['shop'] = 'tuner',
    },
	['r35'] = {
        ['name'] = 'R35 GTR',
        ['brand'] = 'Nissan',
        ['model'] = 'r35',
        ['price'] = 120000,
        ['category'] = 'tuner',
        ['hash'] = `r35`,
        ['shop'] = 'tuner',
    },
	['nisgtsrr31'] = {
        ['name'] = 'GTSR Skyline',
        ['brand'] = 'Nissan',
        ['model'] = 'nisgtsrr31',
        ['price'] = 120000,
        ['category'] = 'tuner',
        ['hash'] = `nisgtsrr31`,
        ['shop'] = 'tuner',
    },
	['nisgtsrr31'] = {
        ['name'] = 'GTSR Skyline',
        ['brand'] = 'Nissan',
        ['model'] = 'nisgtsrr31',
        ['price'] = 120000,
        ['category'] = 'tuner',
        ['hash'] = `nisgtsrr31`,
        ['shop'] = 'tuner',
    },
	['nis14'] = {
        ['name'] = 'S14',
        ['brand'] = 'Nissan',
        ['model'] = 'nis14',
        ['price'] = 120000,
        ['category'] = 'tuner',
        ['hash'] = `nis14`,
        ['shop'] = 'tuner',
    },
	['m3e30'] = {
        ['name'] = 'M3 E30',
        ['brand'] = 'BMW',
        ['model'] = 'm3e30',
        ['price'] = 120000,
        ['category'] = 'tuner',
        ['hash'] = `m3e30`,
        ['shop'] = 'tuner',
    },
	['toy86'] = {
        ['name'] = 'GT 86',
        ['brand'] = 'Toyota',
        ['model'] = 'toy86',
        ['price'] = 120000,
        ['category'] = 'tuner',
        ['hash'] = `toy86`,
        ['shop'] = 'tuner',
    },
	['gsx'] = {
        ['name'] = 'GSX',
        ['brand'] = 'Mitsubishi',
        ['model'] = 'gsx',
        ['price'] = 120000,
        ['category'] = 'tuner',
        ['hash'] = `gsx`,
        ['shop'] = 'tuner',
    },
	['gc10'] = {
        ['name'] = '2000 GT',
        ['brand'] = 'Nissan',
        ['model'] = 'gc10',
        ['price'] = 120000,
        ['category'] = 'tuner',
        ['hash'] = `gc10`,
        ['shop'] = 'tuner',
    },
	['mitgalant92'] = {
        ['name'] = '1992 Galant',
        ['brand'] = 'Mitsubishi',
        ['model'] = 'mitgalant92',
        ['price'] = 120000,
        ['category'] = 'tuner',
        ['hash'] = `mitgalant92`,
        ['shop'] = 'tuner',
    },
	['mitgalant92'] = {
        ['name'] = '1992 Galant',
        ['brand'] = 'Mitsubishi',
        ['model'] = 'mitgalant92',
        ['price'] = 120000,
        ['category'] = 'tuner',
        ['hash'] = `mitgalant92`,
        ['shop'] = 'tuner',
    },
	['fdviper'] = {
        ['name'] = 'FD Viper',
        ['brand'] = 'Dodge',
        ['model'] = 'fdviper',
        ['price'] = 120000,
        ['category'] = 'tuner',
        ['hash'] = `fdviper`,
        ['shop'] = 'tuner',
    },
	['fd'] = {
        ['name'] = 'RX7 FD',
        ['brand'] = 'Mazda',
        ['model'] = 'fd',
        ['price'] = 120000,
        ['category'] = 'tuner',
        ['hash'] = `fd`,
        ['shop'] = 'tuner',
    },
	['mfc'] = {
        ['name'] = 'RX7 FC',
        ['brand'] = 'Mazda',
        ['model'] = 'mfc',
        ['price'] = 120000,
        ['category'] = 'tuner',
        ['hash'] = `mfc`,
        ['shop'] = 'tuner',
    },
	['f40'] = {
        ['name'] = 'F40',
        ['brand'] = 'Ferrari',
        ['model'] = 'f40',
        ['price'] = 120000,
        ['category'] = 'tuner',
        ['hash'] = `f40`,
        ['shop'] = 'tuner',
    },
	['f512tr'] = {
        ['name'] = 'F512',
        ['brand'] = 'Ferrari',
        ['model'] = 'f512tr',
        ['price'] = 120000,
        ['category'] = 'tuner',
        ['hash'] = `f512tr`,
        ['shop'] = 'tuner',
    },
	['f512tr'] = {
        ['name'] = 'F512',
        ['brand'] = 'Ferrari',
        ['model'] = 'f512tr',
        ['price'] = 120000,
        ['category'] = 'tuner',
        ['hash'] = `f512tr`,
        ['shop'] = 'tuner',
    },
	['f8hrs'] = {
        ['name'] = 'F8',
        ['brand'] = 'Ferrari',
        ['model'] = 'f8hrs',
        ['price'] = 120000,
        ['category'] = 'tuner',
        ['hash'] = `f8hrs`,
        ['shop'] = 'tuner',
    },
	['evo9'] = {
        ['name'] = 'Evo 9',
        ['brand'] = 'Mitsubishi',
        ['model'] = 'evo9',
        ['price'] = 120000,
        ['category'] = 'tuner',
        ['hash'] = `evo9`,
        ['shop'] = 'tuner',
    },
	['er34n'] = {
        ['name'] = 'ER34',
        ['brand'] = 'Nissan',
        ['model'] = 'er34n',
        ['price'] = 120000,
        ['category'] = 'tuner',
        ['hash'] = `er34n`,
        ['shop'] = 'tuner',
    },
	['ek9'] = {
        ['name'] = 'EK9',
        ['brand'] = 'Honda',
        ['model'] = 'ek9',
        ['price'] = 120000,
        ['category'] = 'tuner',
        ['hash'] = `ek9`,
        ['shop'] = 'tuner',
    },
	['ecr33'] = {
        ['name'] = 'GTS25 Skyline',
        ['brand'] = 'Nissan',
        ['model'] = 'ecr33',
        ['price'] = 120000,
        ['category'] = 'tuner',
        ['hash'] = `ecr33`,
        ['shop'] = 'tuner',
    },
	['honcrx91'] = {
        ['name'] = '1991 CRX',
        ['brand'] = 'Honda',
        ['model'] = 'honcrx91',
        ['price'] = 120000,
        ['category'] = 'tuner',
        ['hash'] = `honcrx91`,
        ['shop'] = 'tuner',
    },
	['honcrx91'] = {
        ['name'] = '1991 CRX',
        ['brand'] = 'Honda',
        ['model'] = 'honcrx91',
        ['price'] = 120000,
        ['category'] = 'tuner',
        ['hash'] = `honcrx91`,
        ['shop'] = 'tuner',
    },
	['cresta90'] = {
        ['name'] = '1990 Cresta',
        ['brand'] = 'Toyota',
        ['model'] = 'cresta90',
        ['price'] = 120000,
        ['category'] = 'tuner',
        ['hash'] = `cresta90`,
        ['shop'] = 'tuner',
    },
	['cresta81'] = {
        ['name'] = '1981 Cresta',
        ['brand'] = 'Toyota',
        ['model'] = 'cresta81',
        ['price'] = 120000,
        ['category'] = 'tuner',
        ['hash'] = `cresta81`,
        ['shop'] = 'tuner',
    },
	['cp9a'] = {
        ['name'] = 'Evo 6',
        ['brand'] = 'Mitsubishi',
        ['model'] = 'cp9a',
        ['price'] = 120000,
        ['category'] = 'tuner',
        ['hash'] = `cp9a`,
        ['shop'] = 'tuner',
    },
	['count5'] = {
        ['name'] = 'Countach',
        ['brand'] = 'Lamborghini',
        ['model'] = 'count5',
        ['price'] = 120000,
        ['category'] = 'tuner',
        ['hash'] = `count5`,
        ['shop'] = 'tuner',
    },
	['chaser90'] = {
        ['name'] = '1990 Chaser',
        ['brand'] = 'Toyota',
        ['model'] = 'chaser90',
        ['price'] = 120000,
        ['category'] = 'tuner',
        ['hash'] = `chaser90`,
        ['shop'] = 'tuner',
    },
	['celsiorucf30'] = {
        ['name'] = '2003 Celsior',
        ['brand'] = 'Toyota',
        ['model'] = 'celsiorucf30',
        ['price'] = 120000,
        ['category'] = 'tuner',
        ['hash'] = `celsiorucf30`,
        ['shop'] = 'tuner',
    },
	['celsiorucf21'] = {
        ['name'] = '1994 Celsior',
        ['brand'] = 'Toyota',
        ['model'] = 'celsiorucf21',
        ['price'] = 120000,
        ['category'] = 'tuner',
        ['hash'] = `celsiorucf21`,
        ['shop'] = 'tuner',
    },
	['celica'] = {
        ['name'] = 'Celica',
        ['brand'] = 'Toyota',
        ['model'] = 'celica',
        ['price'] = 120000,
        ['category'] = 'tuner',
        ['hash'] = `celica`,
        ['shop'] = 'tuner',
    },
	['celica'] = {
        ['name'] = 'Celica',
        ['brand'] = 'Toyota',
        ['model'] = 'celica',
        ['price'] = 120000,
        ['category'] = 'tuner',
        ['hash'] = `celica`,
        ['shop'] = 'tuner',
    },
	['c33s13'] = {
        ['name'] = 'C33 S13',
        ['brand'] = 'Nissan',
        ['model'] = 'c33s13',
        ['price'] = 120000,
        ['category'] = 'tuner',
        ['hash'] = `c33s13`,
        ['shop'] = 'tuner',
    },
	['c33s13'] = {
        ['name'] = 'C33 S13',
        ['brand'] = 'Nissan',
        ['model'] = 'c33s13',
        ['price'] = 120000,
        ['category'] = 'tuner',
        ['hash'] = `c33s13`,
        ['shop'] = 'tuner',
    },
	['bnr34'] = {
        ['name'] = 'R34 Skyline',
        ['brand'] = 'Nissan',
        ['model'] = 'bnr34',
        ['price'] = 120000,
        ['category'] = 'tuner',
        ['hash'] = `bnr34`,
        ['shop'] = 'tuner',
    },
	['amuses2k'] = {
        ['name'] = 'Amuse S2000',
        ['brand'] = 'Honda',
        ['model'] = 'amuses2k',
        ['price'] = 120000,
        ['category'] = 'tuner',
        ['hash'] = `amuses2k`,
        ['shop'] = 'tuner',
    },
	['amuses2k'] = {
        ['name'] = 'Amuse S2000',
        ['brand'] = 'Honda',
        ['model'] = 'amuses2k',
        ['price'] = 120000,
        ['category'] = 'tuner',
        ['hash'] = `amuses2k`,
        ['shop'] = 'tuner',
    },
	['amgbs'] = {
        ['name'] = 'GT AMG',
        ['brand'] = 'Mercedes',
        ['model'] = 'amgbs',
        ['price'] = 120000,
        ['category'] = 'tuner',
        ['hash'] = `amgbs`,
        ['shop'] = 'tuner',
    },
	['altezza'] = {
        ['name'] = 'Altezza',
        ['brand'] = 'Toyota',
        ['model'] = 'altezza',
        ['price'] = 120000,
        ['category'] = 'tuner',
        ['hash'] = `altezza`,
        ['shop'] = 'tuner',
    },
	['ae86'] = {
        ['name'] = 'AE86',
        ['brand'] = 'Toyota',
        ['model'] = 'ae86',
        ['price'] = 120000,
        ['category'] = 'tuner',
        ['hash'] = `ae86`,
        ['shop'] = 'tuner',
    },
	['jza70'] = {
        ['name'] = 'JZA70 Supra',
        ['brand'] = 'Toyota',
        ['model'] = 'jza70',
        ['price'] = 120000,
        ['category'] = 'tuner',
        ['hash'] = `jza70`,
        ['shop'] = 'tuner',
    },
	['911r'] = {
        ['name'] = '911 GT3',
        ['brand'] = 'Porsche',
        ['model'] = '911r',
        ['price'] = 120000,
        ['category'] = 'tuner',
        ['hash'] = `911r`,
        ['shop'] = 'tuner',
    },
	['911r'] = {
        ['name'] = '911 GT3',
        ['brand'] = 'Porsche',
        ['model'] = '911r',
        ['price'] = 120000,
        ['category'] = 'tuner',
        ['hash'] = `911r`,
        ['shop'] = 'tuner',
    },
	['850'] = {
        ['name'] = '850 CSi',
        ['brand'] = 'BMW',
        ['model'] = '850',
        ['price'] = 120000,
        ['category'] = 'tuner',
        ['hash'] = `850`,
        ['shop'] = 'tuner',
    },
	['458it'] = {
        ['name'] = '458',
        ['brand'] = 'Ferrari',
        ['model'] = '458it',
        ['price'] = 120000,
        ['category'] = 'tuner',
        ['hash'] = `458it`,
        ['shop'] = 'tuner',
    },
	['350zstardast'] = {
        ['name'] = 'Stardast 350z',
        ['brand'] = 'Nissan',
        ['model'] = '350zstardast',
        ['price'] = 120000,
        ['category'] = 'tuner',
        ['hash'] = `350zstardast`,
        ['shop'] = 'tuner',
    },
	['350zstardast'] = {
        ['name'] = 'Stardast 350z',
        ['brand'] = 'Nissan',
        ['model'] = '350zstardast',
        ['price'] = 120000,
        ['category'] = 'tuner',
        ['hash'] = `350zstardast`,
        ['shop'] = 'tuner',
    },
	['190e'] = {
        ['name'] = '190e',
        ['brand'] = 'Mercedes',
        ['model'] = '190e',
        ['price'] = 120000,
        ['category'] = 'tuner',
        ['hash'] = `190e`,
        ['shop'] = 'tuner',
    },
	['nis180'] = {
        ['name'] = '180sx',
        ['brand'] = 'Nissan',
        ['model'] = 'nis180',
        ['price'] = 120000,
        ['category'] = 'tuner',
        ['hash'] = `nis180`,
        ['shop'] = 'tuner',
    },
	['daisx'] = {
        ['name'] = 'Discount Tire 180sx',
        ['brand'] = 'Nissan',
        ['model'] = 'daisx',
        ['price'] = 120000,
        ['category'] = 'tuner',
        ['hash'] = `daisx`,
        ['shop'] = 'tuner',
    },
	['350z'] = {
        ['name'] = '350z',
        ['brand'] = 'Nissan',
        ['model'] = '350z',
        ['price'] = 120000,
        ['category'] = 'tuner',
        ['hash'] = `350z`,
        ['shop'] = 'tuner',
    },
	['720s'] = {
        ['name'] = '720s',
        ['brand'] = 'Mclaren',
        ['model'] = '720s',
        ['price'] = 120000,
        ['category'] = 'tuner',
        ['hash'] = `720s`,
        ['shop'] = 'tuner',
    },
	['720s'] = {
        ['name'] = '720s',
        ['brand'] = 'Mclaren',
        ['model'] = '720s',
        ['price'] = 120000,
        ['category'] = 'tuner',
        ['hash'] = `720s`,
        ['shop'] = 'tuner',
    },
	['2000gtr'] = {
        ['name'] = '2000 GTR',
        ['brand'] = 'Nissan',
        ['model'] = '2000gtr',
        ['price'] = 120000,
        ['category'] = 'tuner',
        ['hash'] = `2000gtr`,
        ['shop'] = 'tuner',
    },
	['a31'] = {
        ['name'] = 'A31',
        ['brand'] = 'Cefiro',
        ['model'] = 'a31',
        ['price'] = 120000,
        ['category'] = 'tuner',
        ['hash'] = `a31`,
        ['shop'] = 'tuner',
    },
	['ae86t'] = {
        ['name'] = 'AE86 Time Attack',
        ['brand'] = 'Toyota',
        ['model'] = 'ae86t',
        ['price'] = 120000,
        ['category'] = 'tuner',
        ['hash'] = `ae86t`,
        ['shop'] = 'tuner',
    },
	['a80tbk'] = {
        ['name'] = 'MK4 Supra Midnight',
        ['brand'] = 'Toyota',
        ['model'] = 'a80tbk',
        ['price'] = 120000,
        ['category'] = 'tuner',
        ['hash'] = `a80tbk`,
        ['shop'] = 'tuner',
    },
	['amis300'] = {
        ['name'] = 'IS 300',
        ['brand'] = 'Lexus',
        ['model'] = 'amis300',
        ['price'] = 120000,
        ['category'] = 'tuner',
        ['hash'] = `amis300`,
        ['shop'] = 'tuner',
    },
	['c63w204'] = {
        ['name'] = 'C63',
        ['brand'] = 'Mercedes',
        ['model'] = 'c63w204',
        ['price'] = 120000,
        ['category'] = 'tuner',
        ['hash'] = `c63w204`,
        ['shop'] = 'tuner',
    },
	['evo3'] = {
        ['name'] = 'Evo 3',
        ['brand'] = 'Mitsubishi',
        ['model'] = 'evo3',
        ['price'] = 120000,
        ['category'] = 'tuner',
        ['hash'] = `evo3`,
        ['shop'] = 'tuner',
    },
	['nis13'] = {
        ['name'] = 'S13',
        ['brand'] = 'Nissan',
        ['model'] = 'nis13',
        ['price'] = 120000,
        ['category'] = 'tuner',
        ['hash'] = `nis13`,
        ['shop'] = 'tuner',
    },
	['nisr32'] = {
        ['name'] = 'R32 Skyline',
        ['brand'] = 'Nissan',
        ['model'] = 'nisr32',
        ['price'] = 120000,
        ['category'] = 'tuner',
        ['hash'] = `nisr32`,
        ['shop'] = 'tuner',
    },
	['nisr33'] = {
        ['name'] = 'R33 Skyline',
        ['brand'] = 'Nissan',
        ['model'] = 'nisr33',
        ['price'] = 120000,
        ['category'] = 'tuner',
        ['hash'] = `nisr33`,
        ['shop'] = 'tuner',
    },
	['r33hr'] = {
        ['name'] = 'HR R33 Skyline',
        ['brand'] = 'Nissan',
        ['model'] = 'r33hr',
        ['price'] = 120000,
        ['category'] = 'tuner',
        ['hash'] = `r33hr`,
        ['shop'] = 'tuner',
    },
	['skyr34'] = {
        ['name'] = 'R34 Skyline 2',
        ['brand'] = 'Nissan',
        ['model'] = 'skyr34',
        ['price'] = 120000,
        ['category'] = 'tuner',
        ['hash'] = `skyr34`,
        ['shop'] = 'tuner',
    },
	['r34mn'] = {
        ['name'] = 'R34 Skyline Midnight',
        ['brand'] = 'Nissan',
        ['model'] = 'r34mn',
        ['price'] = 120000,
        ['category'] = 'tuner',
        ['hash'] = `r34mn`,
        ['shop'] = 'tuner',
    },
	['nissil80'] = {
        ['name'] = 'Sleighty',
        ['brand'] = 'Nissan',
        ['model'] = 'nissil80',
        ['price'] = 120000,
        ['category'] = 'tuner',
        ['hash'] = `nissil80`,
        ['shop'] = 'tuner',
    },
	['benzsl63'] = {
        ['name'] = 'SL63',
        ['brand'] = 'Mercedes',
        ['model'] = 'benzsl63',
        ['price'] = 120000,
        ['category'] = 'tuner',
        ['hash'] = `benzsl63`,
        ['shop'] = 'tuner',
    },
	['toysupmk4'] = {
        ['name'] = 'MK4 Supra',
        ['brand'] = 'Toyota',
        ['model'] = 'toysupmk4',
        ['price'] = 120000,
        ['category'] = 'tuner',
        ['hash'] = `toysupmk4`,
        ['shop'] = 'tuner',
    },
	['z32'] = {
        ['name'] = 'Z32',
        ['brand'] = 'Nissan',
        ['model'] = 'z32',
        ['price'] = 120000,
        ['category'] = 'tuner',
        ['hash'] = `z32`,
        ['shop'] = 'tuner',
    },
	['nscw'] = {
        ['name'] = 'R34 Skyline CW',
        ['brand'] = 'Nissan',
        ['model'] = 'nscw',
        ['price'] = 120000,
        ['category'] = 'tuner',
        ['hash'] = `nscw`,
        ['shop'] = 'tuner',
    },
	['evovaris'] = {
        ['name'] = 'Varis EVO',
        ['brand'] = 'Mitsubishi',
        ['model'] = 'evovaris',
        ['price'] = 120000,
        ['category'] = 'tuner',
        ['hash'] = `evovaris`,
        ['shop'] = 'tuner',
    },
}

for _, v in pairs(QBShared.Vehicles) do
	QBShared.VehicleHashes[v.hash] = v
end
