------------------- start of pdm ------------
	--[[

	['golfmk6'] = {
		['name'] = 'Golf MK6',
		['brand'] = 'Volkswagen',
		['model'] = 'golfmk6',
		['price'] = 14500,
		['category'] = 'pimports',
		['hash'] = `golfmk6`,
		['shop'] = 'pdm',
		['tier'] = 'B',
	},
	['sienna'] = {
		['name'] = 'Sienna',
		['brand'] = 'Toyota',
		['model'] = 'sienna',
		['price'] = 19000,
		['category'] = 'pimports',
		['hash'] = `sienna`,
		['shop'] = 'pdm',
	},
	['camry55'] = {
		['name'] = '2016 Camry',
		['brand'] = 'Toyota',
		['model'] = 'camry55',
		['price'] = 16000,
		['category'] = 'pimports',
		['hash'] = `camry55`,
		['shop'] = 'pdm',
	},
	['camry18'] = {
		['name'] = '2018 Camry',
		['brand'] = 'Toyota',
		['model'] = 'camry18',
		['price'] = 21000,
		['category'] = 'pimports',
		['hash'] = `camry18`,
		['shop'] = 'pdm',
	},
	['gto65'] = {
		['name'] = '1965 GTO',
		['brand'] = 'Pontiac',
		['model'] = 'gto65',
		['price'] = 29000,
		['category'] = 'pimports',
		['hash'] = `gto65`,
		['shop'] = 'pdm',
	},
	['rogue20'] = {
		['name'] = '2020 Rogue',
		['brand'] = 'Nissan',
		['model'] = 'rogue20',
		['price'] = 27000,
		['category'] = 'pimports',
		['hash'] = `rogue20`,
		['shop'] = 'pdm',
	},
	['qashqai16'] = {
		['name'] = '2016 Qash Qai',
		['brand'] = 'Nissan',
		['model'] = 'qashqai16',
		['price'] = 28000,
		['category'] = 'pimports',
		['hash'] = `qashqai16`,
		['shop'] = 'pdm',
	},
	['nisaltima'] = {
		['name'] = 'Altima',
		['brand'] = 'Nissan',
		['model'] = 'nisaltima',
		['price'] = 16000,
		['category'] = 'pimports',
		['hash'] = `nisaltima`,
		['shop'] = 'pdm',
	},
	['optima'] = {
		['name'] = 'Optima',
		['brand'] = 'Kia',
		['model'] = 'optima',
		['price'] = 22000,
		['category'] = 'pimports',
		['hash'] = `optima`,
		['shop'] = 'pdm',
	},
	['fx50s'] = {
		['name'] = 'FX50s',
		['brand'] = 'Infiniti',
		['model'] = 'fx50s',
		['price'] = 29000,
		['category'] = 'pimports',
		['hash'] = `fx50s`,
		['shop'] = 'pdm',
	},
	['honody'] = {
		['name'] = '2018 Odyssey',
		['brand'] = 'Honda',
		['model'] = 'honody',
		['price'] = 27000,
		['category'] = 'pimports',
		['hash'] = `honody`,
		['shop'] = 'pdm',
	},
	['accord20'] = {
		['name'] = '2020 Accord',
		['brand'] = 'Honda',
		['model'] = 'accord20',
		['price'] = 22000,
		['category'] = 'pimports',
		['hash'] = `accord20`,
		['shop'] = 'pdm',
		['tier'] = 'B',
	},
	['taki428'] = {
		['name'] = '1969 GT500',
		['brand'] = 'Ford',
		['model'] = 'taki428',
		['price'] = 19000,
		['category'] = 'pimports',
		['hash'] = `taki428`,
		['shop'] = 'pdm',
		['tier'] = 'D',
	},
	['focusrs'] = {
		['name'] = '2017 Focus',
		['brand'] = 'Ford',
		['model'] = 'focusrs',
		['price'] = 29000,
		['category'] = 'pimports',
		['hash'] = `focusrs`,
		['shop'] = 'pdm',
	},
	['f15078'] = {
		['name'] = '1978 F150',
		['brand'] = 'Ford',
		['model'] = 'f15078',
		['price'] = 17000,
		['category'] = 'pimports',
		['hash'] = `f15078`,
		['shop'] = 'pdm',
	},
	['crownvic2011'] = {
		['name'] = '2011 Crown Vic',
		['brand'] = 'Ford',
		['model'] = 'crownvic2011',
		['price'] = 7000,
		['category'] = 'pimports',
		['hash'] = `crownvic2011`,
		['shop'] = 'pdm',
	},
	['mustang65'] = {
		['name'] = '1965 Mustang',
		['brand'] = 'Ford',
		['model'] = 'mustang65',
		['price'] = 22000,
		['category'] = 'pimports',
		['hash'] = `mustang65`,
		['shop'] = 'pdm',
		['tier'] = 'C',
	},
	['mgt'] = {
		['name'] = '2018 Mustang',
		['brand'] = 'Ford',
		['model'] = 'mgt',
		['price'] = 38000,
		['category'] = 'pimports',
		['hash'] = `mgt`,
		['shop'] = 'pdm',
		['tier'] = 'B',
	},
	['rakchr'] = {
		['name'] = '2015 Charger SE',
		['brand'] = 'Dodge',
		['model'] = 'rakchr',
		['price'] = 31000,
		['category'] = 'pimports',
		['hash'] = `rakchr`,
		['shop'] = 'pdm',
	},
	['68dart'] = {
		['name'] = '1968 Dart',
		['brand'] = 'Dodge',
		['model'] = '68dart',
		['price'] = 13000,
		['category'] = 'pimports',
		['hash'] = `68dart`,
		['shop'] = 'pdm',
	},
	['69charger'] = {
		['name'] = '1969 Charger',
		['brand'] = 'Dodge',
		['model'] = '69charger',
		['price'] = 70000,
		['category'] = 'pimports',
		['hash'] = `69charger`,
		['shop'] = 'pdm',
		['tier'] = 'C',
	},
	['czr1'] = {
		['name'] = '2019 CZR1',
		['brand'] = 'Chevy',
		['model'] = 'czr1',
		['price'] = 90000,
		['category'] = 'pimports',
		['hash'] = `czr1`,
		['shop'] = 'pdm',
		['tier'] = 'B',
	},
	['z2879'] = {
		['name'] = '1979 Z28',
		['brand'] = 'Chevy',
		['model'] = 'z2879',
		['price'] = 7000,
		['category'] = 'pimports',
		['hash'] = `z2879`,
		['shop'] = 'pdm',
	},
	['gmt900escalade'] = {
		['name'] = '2012 Escalade',
		['brand'] = 'Cadallac',
		['model'] = 'gmt900escalade',
		['price'] = 62000,
		['category'] = 'pimports',
		['hash'] = `gmt900escalade`,
		['shop'] = 'pdm',
	},
	['m6f13'] = {
		['name'] = '2013 M6',
		['brand'] = 'BMW',
		['model'] = 'm6f13',
		['price'] = 45000,
		['category'] = 'pimports',
		['hash'] = `m6f13`,
		['shop'] = 'pdm',
	},
	['m2f22'] = {
		['name'] = '2016 M2',
		['brand'] = 'BMW',
		['model'] = 'm2f22',
		['price'] = 45000,
		['category'] = 'pimports',
		['hash'] = `m2f22`,
		['shop'] = 'pdm',
	},
	['a6'] = {
		['name'] = 'A6',
		['brand'] = 'Audi',
		['model'] = 'a6',
		['price'] = 55000,
		['category'] = 'pimports',
		['hash'] = `a6`,
		['shop'] = 'pdm',
	},
	['gs350'] = {
		['name'] = 'GS 350',
		['brand'] = 'Lexus',
		['model'] = 'gs350',
		['price'] = 47000,
		['category'] = 'pimports',
		['hash'] = `gs350`,
		['shop'] = 'pdm',
	},
	]]--

	------ END OF PDM ------------


    -- rmod --
	['rmodi8ks'] = {
        ['name'] = 'I8 KS',
        ['brand'] = 'BMW',
        ['model'] = 'rmodi8ks',
        ['price'] = 1000000,
        ['category'] = 'imports',
        ['hash'] = `rmodi8ks`,
        ['shop'] = {'ottos',}
    },
	['rmod918spyder'] = {
        ['name'] = '918 Spyder',
        ['brand'] = 'Porsche',
        ['model'] = 'rmod918spyder',
        ['price'] = 1000000,
        ['category'] = 'imports',
        ['hash'] = `rmod918spyder`,
        ['shop'] = {'ottos',}
    },
	['rmodbentayga'] = {
        ['name'] = 'Bentayga',
        ['brand'] = 'Bentley',
        ['model'] = 'rmodbentayga',
        ['price'] = 1000000,
        ['category'] = 'imports',
        ['hash'] = `rmodbentayga`,
        ['shop'] = {'ottos',}
    },
	['rmodr8alpil'] = {
        ['name'] = 'R8 Alpil',
        ['brand'] = 'Audi',
        ['model'] = 'rmodr8alpil',
        ['price'] = 1000000,
        ['category'] = 'imports',
        ['hash'] = `rmodr8alpil`,
        ['shop'] = {'ottos',}
    },
	['rmodsennagtr'] = {
        ['name'] = 'Senna GTR',
        ['brand'] = 'Mclaren',
        ['model'] = 'rmodsennagtr',
        ['price'] = 1000000,
        ['category'] = 'imports',
        ['hash'] = `rmodsennagtr`,
        ['shop'] = {'ottos',}
    },
	['rmodcharger'] = {
        ['name'] = 'Hellcat Charger',
        ['brand'] = 'Dodge',
        ['model'] = 'rmodcharger',
        ['price'] = 1000000,
        ['category'] = 'imports',
        ['hash'] = `rmodcharger`,
        ['shop'] = {'ottos',}
    },
	['rmodf8'] = {
        ['name'] = 'F8',
        ['brand'] = 'Ferrari',
        ['model'] = 'rmodf8',
        ['price'] = 1000000,
        ['category'] = 'imports',
        ['hash'] = `rmodf8`,
        ['shop'] = {'ottos',}
    },
	['rmodjeepg'] = {
        ['name'] = 'Gladiator',
        ['brand'] = 'Jeep',
        ['model'] = 'rmodjeepg',
        ['price'] = 1000000,
        ['category'] = 'imports',
        ['hash'] = `rmodjeepg`,
        ['shop'] = {'ottos',}
    },
	['rmod911gt3'] = {
        ['name'] = '911 GT3',
        ['brand'] = 'Porsche',
        ['model'] = 'rmod911gt3',
        ['price'] = 1000000,
        ['category'] = 'imports',
        ['hash'] = `rmod911gt3`,
        ['shop'] = {'ottos',}
    },
	['rmodr8v10'] = {
        ['name'] = 'R8 V10',
        ['brand'] = 'Audi',
        ['model'] = 'rmodr8v10',
        ['price'] = 1000000,
        ['category'] = 'imports',
        ['hash'] = `rmodr8v10`,
        ['shop'] = {'ottos',}
    },
	['rmodquadra'] = {
        ['name'] = 'Quadra',
        ['brand'] = 'Audi',
        ['model'] = 'rmodquadra',
        ['price'] = 1000000,
        ['category'] = 'imports',
        ['hash'] = `rmodquadra`,
        ['shop'] = {'ottos',}
    },
	['rmodsupralb'] = {
        ['name'] = 'Supra LB WLK',
        ['brand'] = 'Toyota',
        ['model'] = 'rmodsupralb',
        ['price'] = 1000000,
        ['category'] = 'imports',
        ['hash'] = `rmodsupralb`,
        ['shop'] = {'ottos',}
    },
	['rmodsuprapandem'] = {
        ['name'] = 'Supra Pandem',
        ['brand'] = 'Toyota',
        ['model'] = 'rmodsuprapandem',
        ['price'] = 1000000,
        ['category'] = 'imports',
        ['hash'] = `rmodsuprapandem`,
        ['shop'] = {'ottos',}
    },
	['rmodz06'] = {
        ['name'] = 'Z06 Corvette',
        ['brand'] = 'Chevy',
        ['model'] = 'rmodz06',
        ['price'] = 1000000,
        ['category'] = 'imports',
        ['hash'] = `rmodz06`,
        ['shop'] = {'ottos',}
    },
	['rmodcamaro69'] = {
        ['name'] = '1969 Camaro',
        ['brand'] = 'Chevy',
        ['model'] = 'rmodcamaro69',
        ['price'] = 1000000,
        ['category'] = 'imports',
        ['hash'] = `rmodcamaro69`,
        ['shop'] = {'ottos',}
    },
	['rmod350zpandem'] = {
        ['name'] = '350z Pandem',
        ['brand'] = 'Nissan',
        ['model'] = 'rmod350zpandem',
        ['price'] = 1000000,
        ['category'] = 'imports',
        ['hash'] = `rmod350zpandem`,
        ['shop'] = {'ottos',}
    },
	['rmodrs5'] = {
        ['name'] = 'RS5',
        ['brand'] = 'Audi',
        ['model'] = 'rmodrs5',
        ['price'] = 1000000,
        ['category'] = 'imports',
        ['hash'] = `rmodrs5`,
        ['shop'] = {'ottos',}
    },

	-- rmod end --

    	-- luxury shop --
	['v877'] = {
        ['name'] = '1977 Vantage',
        ['brand'] = 'Aston Martin',
        ['model'] = 'v877',
        ['price'] = 85000,
        ['category'] = 'imports',
        ['hash'] = `v877`,
        ['shop'] = {'luxury', 'imports', 'ottos',  'autoex',}
    },
	['db11'] = {
        ['name'] = '2017 DB11',
        ['brand'] = 'Aston Martin',
        ['model'] = 'db11',
        ['price'] = 215000,
        ['category'] = 'imports',
        ['hash'] = `db11`,
        ['shop'] = {'luxury', 'imports', 'ottos',  'autoex',}
    },
	['vulcan'] = {
        ['name'] = 'Vulcan',
        ['brand'] = 'Aston Martin',
        ['model'] = 'vulcan',
        ['price'] = 2300000,
        ['category'] = 'imports',
        ['hash'] = `vulcan`,
        ['shop'] = {'luxury', 'imports', 'ottos',  'autoex',}
    },
	['victor'] = {
        ['name'] = 'Victor',
        ['brand'] = 'Aston Martin',
        ['model'] = 'victor',
        ['price'] = 3800000,
        ['category'] = 'imports',
        ['hash'] = `victor`,
        ['shop'] = {'luxury', 'imports', 'ottos',  'autoex',}
    },
	['rmodmartin'] = {
        ['name'] = '2021 DB11',
        ['brand'] = 'Aston Martin',
        ['model'] = 'rmodmartin',
        ['price'] = 320000,
        ['category'] = 'imports',
        ['hash'] = `rmodmartin`,
        ['shop'] = {'luxury', 'imports', 'ottos',  'autoex', 'hayes',},
		['tier'] = 'A+',
    },
	['rmodr8c'] = {
        ['name'] = 'R8 Convertible',
        ['brand'] = 'Audi',
        ['model'] = 'rmodr8c',
        ['price'] = 160000,
        ['category'] = 'imports',
        ['hash'] = `rmodr8c`,
        ['shop'] = {'luxury', 'imports', 'ottos',  'autoex', 'hayes',},
		['tier'] = 'A',
    },
	['rmodrs6'] = {
        ['name'] = '2020 RS6',
        ['brand'] = 'Audi',
        ['model'] = 'rmodrs6',
        ['price'] = 90000,
        ['category'] = 'imports',
        ['hash'] = `rmodrs6`,
        ['shop'] = {'luxury', 'imports', 'ottos',  'autoex', 'hayes',},
		['tier'] = 'A',
    },
	['rmodrs6r'] = {
        ['name'] = '2020 RS6R',
        ['brand'] = 'Audi',
        ['model'] = 'rmodrs6r',
        ['price'] = 97000,
        ['category'] = 'imports',
        ['hash'] = `rmodrs6r`,
        ['shop'] = {'luxury', 'imports', 'ottos',  'autoex', 'hayes',},
		['tier'] = 'A+',
    },
	['22m5'] = {
        ['name'] = '2022 M5',
        ['brand'] = 'BMW',
        ['model'] = '22m5',
        ['price'] = 110000,
        ['category'] = 'imports',
        ['hash'] = `22m5`,
        ['shop'] = {'luxury', 'imports', 'ottos',  'autoex', 'hayes',},
    },
	['bs17'] = {
        ['name'] = 'S1000 RR',
        ['brand'] = 'BMW',
        ['model'] = 'bs17',
        ['price'] = 17000,
        ['category'] = 'imports',
        ['hash'] = `bs17`,
        ['shop'] = {'luxury', 'imports', 'ottos',  'autoex', 'hayes',},
    },
	['e92'] = {
        ['name'] = '2008 M3',
        ['brand'] = 'BMW',
        ['model'] = 'e92',
        ['price'] = 35000,
        ['category'] = 'imports',
        ['hash'] = `e92`,
        ['shop'] = {'luxury', 'imports', 'ottos',  'autoex', 'hayes',},
		['tier'] = 'C',
    },
	['m4f82'] = {
        ['name'] = '2015 M4',
        ['brand'] = 'BMW',
        ['model'] = 'm4f82',
        ['price'] = 35000,
        ['category'] = 'imports',
        ['hash'] = `m4f82`,
        ['shop'] = {'luxury', 'imports', 'ottos',  'autoex', 'hayes',},
    },
	['rmodm5e34'] = {
        ['name'] = '1995 M5',
        ['brand'] = 'BMW',
        ['model'] = 'rmodm5e34',
        ['price'] = 85000,
        ['category'] = 'imports',
        ['hash'] = `rmodm5e34`,
        ['shop'] = {'luxury', 'imports', 'ottos',  'autoex', 'hayes',},
    },
	['bdivo'] = {
        ['name'] = '2019 Divo',
        ['brand'] = 'Bugatti',
        ['model'] = 'bdivo',
        ['price'] = 5800000,
        ['category'] = 'imports',
        ['hash'] = `bdivo`,
        ['shop'] = {'luxury', 'imports', 'ottos',  'autoex', 'hayes',},
    },
	['chiron17'] = {
        ['name'] = '2017 Chiron',
        ['brand'] = 'Bugatti',
        ['model'] = 'chiron17',
        ['price'] = 4300000,
        ['category'] = 'imports',
        ['hash'] = `chiron17`,
        ['shop'] = {'luxury', 'imports', 'ottos',  'autoex', 'hayes',},
    },
	['bolide'] = {
        ['name'] = '2020 Bolide',
        ['brand'] = 'Bugatti',
        ['model'] = 'bolide',
        ['price'] = 9000000,
        ['category'] = 'imports',
        ['hash'] = `bolide`,
        ['shop'] = {'luxury', 'imports', 'ottos',  'autoex', 'hayes',},
    },
	['supersport'] = {
        ['name'] = '2010 Supersport',
        ['brand'] = 'Bugatti',
        ['model'] = 'supersport',
        ['price'] = 3300000,
        ['category'] = 'imports',
        ['hash'] = `supersport`,
        ['shop'] = {'luxury', 'imports', 'ottos',  'autoex', 'hayes',},
    },
	['exor'] = {
        ['name'] = 'Hennessey Camaro',
        ['brand'] = 'Chevy',
        ['model'] = 'exor',
        ['price'] = 155000,
        ['category'] = 'imports',
        ['hash'] = `exor`,
        ['shop'] = {'luxury', 'imports', 'ottos',  'autoex', 'hayes',},
    },
	['c8corvette'] = {
        ['name'] = '2020 C8',
        ['brand'] = 'Chevy',
        ['model'] = 'c8corvette',
        ['price'] = 78000,
        ['category'] = 'imports',
        ['hash'] = `c8corvette`,
        ['shop'] = {'luxury', 'imports', 'ottos',  'autoex', 'hayes',},
    },
	['acr'] = {
        ['name'] = '2016 Viper ACR',
        ['brand'] = 'Dodge',
        ['model'] = 'acr',
        ['price'] = 120000,
        ['category'] = 'imports',
        ['hash'] = `acr`,
        ['shop'] = {'luxury', 'imports', 'ottos',  'autoex', 'hayes',},
		['tier'] = 'A',
    },
	['nixpycharger21'] = {
        ['name'] = '2021 Hellcat Charger',
        ['brand'] = 'Dodge',
        ['model'] = 'nixpycharger21',
        ['price'] = 85000,
        ['category'] = 'imports',
        ['hash'] = `nixpycharger21`,
        ['shop'] = {'luxury', 'imports', 'ottos',  'autoex', 'hayes',},
		['tier'] = 'A',
    },
	['rmodcharger69'] = {
        ['name'] = '1969 Charger',
        ['brand'] = 'Dodge',
        ['model'] = 'rmodcharger69',
        ['price'] = 89000,
        ['category'] = 'imports',
        ['hash'] = `rmodcharger69`,
        ['shop'] = {'luxury', 'imports', 'ottos',  'autoex', 'hayes',},
    },
	['vip8'] = {
        ['name'] = '2008 Viper',
        ['brand'] = 'Dodge',
        ['model'] = 'vip8',
        ['price'] = 62000,
        ['category'] = 'imports',
        ['hash'] = `vip8`,
        ['shop'] = {'luxury', 'imports', 'ottos',  'autoex', 'hayes',},
		['tier'] = 'B',
    },
	['rmodf40'] = {
        ['name'] = 'F40',
        ['brand'] = 'Ferrari',
        ['model'] = 'rmodf40',
        ['price'] = 1500000,
        ['category'] = 'imports',
        ['hash'] = `rmodf40`,
        ['shop'] = {'luxury', 'imports', 'ottos',  'autoex', 'hayes',},
		['tier'] = 'S',
    },
	['gt17'] = {
        ['name'] = '2017 GT',
        ['brand'] = 'Ford',
        ['model'] = 'gt17',
        ['price'] = 500000,
        ['category'] = 'imports',
        ['hash'] = `gt17`,
        ['shop'] = {'luxury', 'imports', 'ottos',  'autoex', 'hayes',},
		['tier'] = 'S+',
    },
	['19raptor'] = {
        ['name'] = '2019 Raptor',
        ['brand'] = 'Ford',
        ['model'] = '19raptor',
        ['price'] = 76000,
        ['category'] = 'imports',
        ['hash'] = `19raptor`,
        ['shop'] = {'luxury', 'imports', 'ottos',  'autoex', 'hayes',},
    },
	['ffrs'] = {
        ['name'] = '2009 Focus',
        ['brand'] = 'Ford',
        ['model'] = 'ffrs',
        ['price'] = 39000,
        ['category'] = 'imports',
        ['hash'] = `ffrs`,
        ['shop'] = {'luxury', 'imports', 'ottos',  'autoex', 'hayes',},
		['tier'] = 'B',
    },
	['mache'] = {
        ['name'] = '2021 Mach E',
        ['brand'] = 'Ford',
        ['model'] = 'mache',
        ['price'] = 46000,
        ['category'] = 'imports',
        ['hash'] = `mache`,
        ['shop'] = {'luxury', 'imports', 'ottos',  'autoex', 'hayes',},
    },
	['rmodescort'] = {
        ['name'] = 'Escort RS',
        ['brand'] = 'Ford',
        ['model'] = 'rmodescort',
        ['price'] = 19000,
        ['category'] = 'imports',
        ['hash'] = `rmodescort`,
        ['shop'] = {'luxury', 'imports', 'ottos',  'autoex', 'hayes',},
		['tier'] = 'B',
    },
	['velociraptor'] = {
        ['name'] = 'Hennessey Velociraptor',
        ['brand'] = 'Ford',
        ['model'] = 'velociraptor',
        ['price'] = 340000,
        ['category'] = 'imports',
        ['hash'] = `velociraptor`,
        ['shop'] = {'luxury', 'imports', 'ottos',  'autoex', 'hayes',},
    },
	['trhawk'] = {
        ['name'] = '2018 Trackhawk',
        ['brand'] = 'Jeep',
        ['model'] = 'trhawk',
        ['price'] = 90000,
        ['category'] = 'imports',
        ['hash'] = `trhawk`,
        ['shop'] = {'luxury', 'imports', 'ottos',  'autoex', 'hayes',},
		['tier'] = 'B',
    },
	['zx10r'] = {
        ['name'] = '2016 ZX10R',
        ['brand'] = 'Kawasaki',
        ['model'] = 'zx10r',
        ['price'] = 16000,
        ['category'] = 'imports',
        ['hash'] = `zx10r`,
        ['shop'] = {'luxury', 'imports', 'ottos',  'autoex', 'hayes',},
    },
	['kiagt'] = {
        ['name'] = 'Stinger GT',
        ['brand'] = 'Kia',
        ['model'] = 'kiagt',
        ['price'] = 36000,
        ['category'] = 'imports',
        ['hash'] = `kiagt`,
        ['shop'] = {'luxury', 'imports', 'ottos',  'autoex', 'hayes',},
		['tier'] = 'B',
    },
	['06sx2t'] = {
        ['name'] = 'SX 125cc',
        ['brand'] = 'KTM',
        ['model'] = '06sx2t',
        ['price'] = 8000,
        ['category'] = 'imports',
        ['hash'] = `06sx2t`,
        ['shop'] = {'luxury', 'imports', 'ottos',  'autoex', 'hayes',},
    },
	['amgone'] = {
        ['name'] = 'AMG One',
        ['brand'] = 'Mercedes',
        ['model'] = 'amgone',
        ['price'] = 2700000,
        ['category'] = 'imports',
        ['hash'] = `amgone`,
        ['shop'] = {'luxury', 'imports', 'ottos',  'autoex', 'hayes',},
		['tier'] = 'S+',
    },
	['rmodlfa'] = {
        ['name'] = 'Lexus LFA',
        ['brand'] = 'Lexus',
        ['model'] = 'rmodlfa',
        ['price'] = 395000,
        ['category'] = 'imports',
        ['hash'] = `rmodlfa`,
        ['shop'] = {'luxury', 'imports', 'ottos',  'autoex', 'hayes',},
		['tier'] = 'S',
    },
	['dredurango'] = {
        ['name'] = 'SRT Durango',
        ['brand'] = 'Dodge',
        ['model'] = 'dredurango',
        ['price'] = 80000,
        ['category'] = 'imports',
        ['hash'] = `dredurango`,
        ['shop'] = {'luxury', 'imports', 'ottos',  'autoex', 'hayes',},
		['tier'] = 'A',
    },
	['lc100'] = {
        ['name'] = 'Land Cruiser',
        ['brand'] = 'Toyota',
        ['model'] = 'lc100',
        ['price'] = 65000,
        ['category'] = 'imports',
        ['hash'] = `lc100`,
        ['shop'] = {'luxury', 'imports', 'ottos',  'autoex', 'hayes',},
    },
	['lp670'] = {
        ['name'] = 'LP670',
        ['brand'] = 'Lamborghini',
        ['model'] = 'lp670',
        ['price'] = 450000,
        ['category'] = 'imports',
        ['hash'] = `lp670`,
        ['shop'] = {'luxury', 'imports', 'ottos',  'autoex', 'hayes',},
    },
	['rmodcamaro'] = {
        ['name'] = '2020 Camaro ZL1',
        ['brand'] = 'Chevy',
        ['model'] = 'rmodcamaro',
        ['price'] = 97000,
        ['category'] = 'imports',
        ['hash'] = `rmodcamaro`,
        ['shop'] = {'luxury', 'imports', 'ottos',  'autoex', 'hayes',},
		['tier'] = 'A',
    },
	['forgt50020'] = {
        ['name'] = '2020 Shelby GT500',
        ['brand'] = 'Ford',
        ['model'] = 'forgt50020',
        ['price'] = 73000,
        ['category'] = 'imports',
        ['hash'] = `forgt50020`,
        ['shop'] = {'luxury', 'imports', 'ottos',  'autoex', 'hayes',},
		['tier'] = 'A',
    },
	['rmodmustang'] = {
        ['name'] = '2015 Mustang GT Widebody',
        ['brand'] = 'Ford',
        ['model'] = 'rmodmustang',
        ['price'] = 92000,
        ['category'] = 'imports',
        ['hash'] = `rmodmustang`,
        ['shop'] = {'luxury', 'imports', 'ottos',  'autoex',}
    },
	['fxxkevo'] = {
        ['name'] = 'FXXK Evo',
        ['brand'] = 'Ferrari',
        ['model'] = 'fxxkevo',
        ['price'] = 2600000,
        ['category'] = 'imports',
        ['hash'] = `fxxkevo`,
        ['shop'] = {'luxury', 'imports', 'ottos',  'autoex',}
    },
	['rmodmk7'] = {
        ['name'] = 'Golf MK7',
        ['brand'] = 'Volkswagen',
        ['model'] = 'rmodmk7',
        ['price'] = 27000,
        ['category'] = 'imports',
        ['hash'] = `rmodmk7`,
        ['shop'] = {'luxury', 'imports', 'ottos',  'autoex',}
    },
	['tr22'] = {
        ['name'] = '2022 Roadster',
        ['brand'] = 'Tesla',
        ['model'] = 'tr22',
        ['price'] = 200000,
        ['category'] = 'imports',
        ['hash'] = `tr22`,
        ['shop'] = {'luxury', 'imports', 'ottos',  'autoex',}
    },
	['teslax'] = {
        ['name'] = 'Model X',
        ['brand'] = 'Tesla',
        ['model'] = 'teslax',
        ['price'] = 120000,
        ['category'] = 'imports',
        ['hash'] = `teslax`,
        ['shop'] = {'luxury', 'imports', 'ottos',  'autoex',}
    },
	['mbc63'] = {
        ['name'] = 'C63 AMG',
        ['brand'] = 'Mercedes',
        ['model'] = 'mbc63',
        ['price'] = 77000,
        ['category'] = 'imports',
        ['hash'] = `mbc63`,
        ['shop'] = {'luxury', 'imports', 'ottos',  'autoex',}
    },
	['gxg63'] = {
        ['name'] = 'G63 AMG',
        ['brand'] = 'Mercedes',
        ['model'] = 'gxg63',
        ['price'] = 132000,
        ['category'] = 'imports',
        ['hash'] = `gxg63`,
        ['shop'] = {'luxury', 'imports', 'ottos',  'autoex',}
    },
	['carsonsgls600'] = {
        ['name'] = 'GLS600',
        ['brand'] = 'Maybach',
        ['model'] = 'carsonsgls600',
        ['price'] = 165000,
        ['category'] = 'imports',
        ['hash'] = `carsonsgls600`,
        ['shop'] = {'luxury', 'imports', 'ottos',  'autoex',}
    },
	['s63mansory18'] = {
        ['name'] = 'S63 Mansory',
        ['brand'] = 'Mansory',
        ['model'] = 's63mansory18',
        ['price'] = 186000,
        ['category'] = 'imports',
        ['hash'] = `s63mansory18`,
        ['shop'] = {'luxury', 'imports', 'ottos',  'autoex',}
    },
	['rcf'] = {
        ['name'] = 'RCF',
        ['brand'] = 'Lexus',
        ['model'] = 'rcf',
        ['price'] = 67000,
        ['category'] = 'imports',
        ['hash'] = `rcf`,
        ['shop'] = {'luxury', 'imports', 'ottos',  'autoex',}
    },
	['carsons392scat'] = {
        ['name'] = 'Scatpack Challenger',
        ['brand'] = 'Dodge',
        ['model'] = 'carsons392scat',
        ['price'] = 47000,
        ['category'] = 'imports',
        ['hash'] = `carsons392scat`,
        ['shop'] = {'luxury', 'imports', 'ottos',  'autoex',}
    },
	['drescatpack'] = {
        ['name'] = 'Scatpack Charger',
        ['brand'] = 'Dodge',
        ['model'] = 'drescatpack',
        ['price'] = 47000,
        ['category'] = 'imports',
        ['hash'] = `drescatpack`,
        ['shop'] = {'luxury', 'imports', 'ottos',  'autoex',}
    },
	['demon'] = {
        ['name'] = '2018 Demon',
        ['brand'] = 'Dodge',
        ['model'] = 'demon',
        ['price'] = 85000,
        ['category'] = 'imports',
        ['hash'] = `demon`,
        ['shop'] = {'luxury', 'imports', 'ottos',  'autoex',}
    },
	['gtam21'] = {
        ['name'] = '2021 Giulia',
        ['brand'] = 'Alfa Romeo',
        ['model'] = 'gtam21',
        ['price'] = 210000,
        ['category'] = 'imports',
        ['hash'] = `gtam21`,
        ['shop'] = {'luxury', 'imports', 'ottos',  'autoex',}
    },
	['audirs6tk'] = {
        ['name'] = '2014 RS6',
        ['brand'] = 'Audi',
        ['model'] = 'audirs6tk',
        ['price'] = 110000,
        ['category'] = 'imports',
        ['hash'] = `audirs6tk`,
        ['shop'] = {'luxury', 'imports', 'ottos',  'autoex',}
    },
	['aventador'] = {
        ['name'] = 'Aventador',
        ['brand'] = 'Lamborghini',
        ['model'] = 'aventador',
        ['price'] = 515000,
        ['category'] = 'imports',
        ['hash'] = `aventador`,
        ['shop'] = {'luxury', 'imports', 'ottos',  'autoex',}
    },
	['q60pbs'] = {
        ['name'] = 'Q60',
        ['brand'] = 'Infiniti',
        ['model'] = 'q60pbs',
        ['price'] = 58000,
        ['category'] = 'imports',
        ['hash'] = `q60pbs`,
        ['shop'] = {'luxury', 'imports', 'ottos',  'autoex',}
    },
	['xnsgt'] = {
        ['name'] = 'Venom GT',
        ['brand'] = 'Hennessey',
        ['model'] = 'xnsgt',
        ['price'] = 3000000,
        ['category'] = 'imports',
        ['hash'] = `xnsgt`,
        ['shop'] = {'luxury', 'imports', 'ottos',  'autoex',}
    },
	['turbo33'] = {
        ['name'] = '33 Turbo',
        ['brand'] = 'Porsche',
        ['model'] = 'turbo33',
        ['price'] = 120000,
        ['category'] = 'imports',
        ['hash'] = `turbo33`,
        ['shop'] = {'luxury', 'imports', 'ottos',  'autoex',}
    },
	['turbo33'] = {
        ['name'] = '33 Turbo',
        ['brand'] = 'Porsche',
        ['model'] = 'turbo33',
        ['price'] = 90000,
        ['category'] = 'imports',
        ['hash'] = `turbo33`,
        ['shop'] = {'luxury', 'imports', 'ottos',  'autoex',}
    },
	['pts21'] = {
        ['name'] = '911 Turbo S',
        ['brand'] = 'Porsche',
        ['model'] = 'pts21',
        ['price'] = 195000,
        ['category'] = 'imports',
        ['hash'] = `pts21`,
        ['shop'] = {'luxury', 'imports', 'ottos',  'autoex',}
    },
	['rmoddarki8'] = {
        ['name'] = 'BMW I8',
        ['brand'] = 'BMW',
        ['model'] = 'rmoddarki8',
        ['price'] = 160000,
        ['category'] = 'imports',
        ['hash'] = `rmoddarki8`,
        ['shop'] = {'luxury', 'imports', 'ottos',  'autoex',}
    },
	['rmodm8c'] = {
        ['name'] = 'M8 Competition',
        ['brand'] = 'BMW',
        ['model'] = 'rmodm8c',
        ['price'] = 110000,
        ['category'] = 'imports',
        ['hash'] = `rmodm8c`,
        ['shop'] = {'luxury', 'imports', 'ottos',  'autoex',}
    },
	['m4comp'] = {
        ['name'] = 'M4 Competition',
        ['brand'] = 'BMW',
        ['model'] = 'm4comp',
        ['price'] = 75000,
        ['category'] = 'imports',
        ['hash'] = `m4comp`,
        ['shop'] = {'luxury', 'imports', 'ottos',  'autoex',}
    },
	['rmode63s'] = {
        ['name'] = 'E63 S',
        ['brand'] = 'Brabus',
        ['model'] = 'rmode63s',
        ['price'] = 507000,
        ['category'] = 'imports',
        ['hash'] = `rmode63s`,
        ['shop'] = {'luxury', 'imports', 'ottos',  'autoex',}
    },
	['rrst'] = {
        ['name'] = 'RR Startech',
        ['brand'] = 'Range Rover',
        ['model'] = 'rrst',
        ['price'] = 135000,
        ['category'] = 'imports',
        ['hash'] = `rrst`,
        ['shop'] = {'luxury', 'imports', 'ottos',  'autoex',}
    },
	['rmodrover'] = {
        ['name'] = 'Mansory Range Rover',
        ['brand'] = 'Range Rover',
        ['model'] = 'rmodrover',
        ['price'] = 320000,
        ['category'] = 'imports',
        ['hash'] = `rmodrover`,
        ['shop'] = {'luxury', 'imports', 'ottos',  'autoex',}
    },
	['rmodg65'] = {
        ['name'] = 'G65 AMG',
        ['brand'] = 'Mercedes',
        ['model'] = 'rmodg65',
        ['price'] = 222000,
        ['category'] = 'imports',
        ['hash'] = `rmodg65`,
        ['shop'] = {'luxury', 'imports', 'ottos',  'autoex',}
    },
	['rmodgt63'] = {
        ['name'] = 'GT63 AMG',
        ['brand'] = 'Mercedes',
        ['model'] = 'rmodgt63',
        ['price'] = 149000,
        ['category'] = 'imports',
        ['hash'] = `rmodgt63`,
        ['shop'] = {'luxury', 'imports', 'ottos',  'autoex',}
    },
	['contss18'] = {
        ['name'] = '',
        ['brand'] = 'Bentley Supersport',
        ['model'] = 'contss18',
        ['price'] = 330000,
        ['category'] = 'imports',
        ['hash'] = `contss18`,
        ['shop'] = {'luxury', 'imports', 'ottos',  'autoex',}
    },

	
	----------------------------------------
	
	-- tuner shop --
	--[[
	['z32midnight'] = {
        ['name'] = 'Z32 Midnight',
        ['brand'] = 'Nissan',
        ['model'] = 'z32midnight',
        ['price'] = 150000,
        ['category'] = 'tuner',
        ['hash'] = `z32midnight`,
        ['shop'] = {'tuner', 'ottos',  'autoex',}
    },
	['subisti08'] = {
        ['name'] = '2008 STI',
        ['brand'] = 'Subaru',
        ['model'] = 'subisti08',
        ['price'] = 135000,
        ['category'] = 'tuner',
        ['hash'] = `subisti08`,
        ['shop'] = {'tuner', 'ottos',  'autoex',}
    },
	['subwrx'] = {
        ['name'] = 'WRX',
        ['brand'] = 'Subaru',
        ['model'] = 'subwrx',
        ['price'] = 120000,
        ['category'] = 'tuner',
        ['hash'] = `subwrx`,
        ['shop'] = {'tuner', 'ottos',  'autoex',}
    },
	['ttrs'] = {
        ['name'] = 'TT RS',
        ['brand'] = 'Audi',
        ['model'] = 'ttrs',
        ['price'] = 115000,
        ['category'] = 'tuner',
        ['hash'] = `ttrs`,
        ['shop'] = {'tuner', 'ottos',  'autoex',}
    },
	['topsecretsupra'] = {
        ['name'] = 'Top Secret Supra',
        ['brand'] = 'Toyota',
        ['model'] = 'topsecretsupra',
        ['price'] = 160000,
        ['category'] = 'tuner',
        ['hash'] = `topsecretsupra`,
        ['shop'] = {'tuner', 'ottos',  'autoex',}
    },
	['tbkr33'] = {
        ['name'] = 'Midnight R33',
        ['brand'] = 'Nissan',
        ['model'] = 'tbkr33',
        ['price'] = 150000,
        ['category'] = 'tuner',
        ['hash'] = `tbkr33`,
        ['shop'] = {'tuner', 'ottos',  'autoex',}
    },
	['a80'] = {
        ['name'] = 'Supra MK4',
        ['brand'] = 'Toyota',
        ['model'] = 'a80',
        ['price'] = 127000,
        ['category'] = 'tuner',
        ['hash'] = `a80`,
        ['shop'] = {'tuner', 'ottos',  'autoex',}
    },
	['mz3'] = {
        ['name'] = 'Speed 3',
        ['brand'] = 'Mazda',
        ['model'] = 'mz3',
        ['price'] = 115000,
        ['category'] = 'tuner',
        ['hash'] = `mz3`,
        ['shop'] = {'tuner', 'ottos',  'autoex',}
    },
	['lexsc300'] = {
        ['name'] = 'SC 300',
        ['brand'] = 'Lexus',
        ['model'] = 'lexsc300',
        ['price'] = 140000,
        ['category'] = 'tuner',
        ['hash'] = `lexsc300`,
        ['shop'] = {'tuner', 'ottos',  'autoex',}
    },
	['ap2'] = {
        ['name'] = 'S2000',
        ['brand'] = 'Honda',
        ['model'] = 'ap2',
        ['price'] = 132000,
        ['category'] = 'tuner',
        ['hash'] = `ap2`,
        ['shop'] = {'tuner', 'ottos',  'autoex',}
    },
	['devilz'] = {
        ['name'] = 'Fairlady Z',
        ['brand'] = 'Nissan',
        ['model'] = 'devilz',
        ['price'] = 140000,
        ['category'] = 'tuner',
        ['hash'] = `devilz`,
        ['shop'] = {'tuner', 'ottos',  'autoex',}
    },
	['s15yokoi'] = {
        ['name'] = 'S15 Yokoi',
        ['brand'] = 'Nissan',
        ['model'] = 's15yokoi',
        ['price'] = 165000,
        ['category'] = 'tuner',
        ['hash'] = `s15yokoi`,
        ['shop'] = {'tuner', 'ottos',  'autoex',}
    },
	['s15worthouse'] = {
        ['name'] = 'S15 Worthouse',
        ['brand'] = 'Nissan',
        ['model'] = 's15worthouse',
        ['price'] = 170000,
        ['category'] = 'tuner',
        ['hash'] = `s15worthouse`,
        ['shop'] = {'tuner', 'ottos',  'autoex',}
    },
	['s15lbwk'] = {
        ['name'] = 'S15 Liberty Walk',
        ['brand'] = 'Nissan',
        ['model'] = 's15lbwk',
        ['price'] = 185000,
        ['category'] = 'tuner',
        ['hash'] = `s15lbwk`,
        ['shop'] = {'tuner', 'ottos',  'autoex',}
    },
	['s14boss'] = {
        ['name'] = 'S14 Boss',
        ['brand'] = 'Nissan',
        ['model'] = 's14boss',
        ['price'] = 145000,
        ['category'] = 'tuner',
        ['hash'] = `s14boss`,
        ['shop'] = {'tuner', 'ottos',  'autoex',}
    },
	['r35'] = {
        ['name'] = 'R35 GTR',
        ['brand'] = 'Nissan',
        ['model'] = 'r35',
        ['price'] = 185000,
        ['category'] = 'tuner',
        ['hash'] = `r35`,
        ['shop'] = {'tuner', 'ottos',  'autoex',}
    },
	['nisgtsrr31'] = {
        ['name'] = 'GTSR Skyline',
        ['brand'] = 'Nissan',
        ['model'] = 'nisgtsrr31',
        ['price'] = 120000,
        ['category'] = 'tuner',
        ['hash'] = `nisgtsrr31`,
        ['shop'] = {'tuner', 'ottos',  'autoex',}
    },
	['nisgtsrr31'] = {
        ['name'] = 'GTSR Skyline',
        ['brand'] = 'Nissan',
        ['model'] = 'nisgtsrr31',
        ['price'] = 165000,
        ['category'] = 'tuner',
        ['hash'] = `nisgtsrr31`,
        ['shop'] = {'tuner', 'ottos',  'autoex',}
    },
	['nis14'] = {
        ['name'] = 'S14',
        ['brand'] = 'Nissan',
        ['model'] = 'nis14',
        ['price'] = 137000,
        ['category'] = 'tuner',
        ['hash'] = `nis14`,
        ['shop'] = {'tuner', 'ottos',  'autoex',}
    },
	['nis15'] = {
        ['name'] = 'S15',
        ['brand'] = 'Nissan',
        ['model'] = 'nis15',
        ['price'] = 137000,
        ['category'] = 'tuner',
        ['hash'] = `nis15`,
        ['shop'] = {'tuner', 'ottos',  'autoex',},
		['tier'] = 'S',
    },
	['m3e30'] = {
        ['name'] = 'M3 E30',
        ['brand'] = 'BMW',
        ['model'] = 'm3e30',
        ['price'] = 132000,
        ['category'] = 'tuner',
        ['hash'] = `m3e30`,
        ['shop'] = {'tuner', 'ottos',  'autoex',}
    },
	['toy86'] = {
        ['name'] = 'GT 86',
        ['brand'] = 'Toyota',
        ['model'] = 'toy86',
        ['price'] = 120000,
        ['category'] = 'tuner',
        ['hash'] = `toy86`,
        ['shop'] = {'tuner', 'ottos',  'autoex',}
    },
	['gsx'] = {
        ['name'] = 'GSX',
        ['brand'] = 'Mitsubishi',
        ['model'] = 'gsx',
        ['price'] = 137000,
        ['category'] = 'tuner',
        ['hash'] = `gsx`,
        ['shop'] = {'tuner', 'ottos',  'autoex',}
    },
	['gc10'] = {
        ['name'] = '2000 GT',
        ['brand'] = 'Nissan',
        ['model'] = 'gc10',
        ['price'] = 155000,
        ['category'] = 'tuner',
        ['hash'] = `gc10`,
        ['shop'] = {'tuner', 'ottos',  'autoex',}
    },
	['mitgalant92'] = {
        ['name'] = '1992 Galant',
        ['brand'] = 'Mitsubishi',
        ['model'] = 'mitgalant92',
        ['price'] = 120000,
        ['category'] = 'tuner',
        ['hash'] = `mitgalant92`,
        ['shop'] = {'tuner', 'ottos',  'autoex',}
    },
	['fdviper'] = {
        ['name'] = 'FD Viper',
        ['brand'] = 'Dodge',
        ['model'] = 'fdviper',
        ['price'] = 215000,
        ['category'] = 'tuner',
        ['hash'] = `fdviper`,
        ['shop'] = {'tuner', 'ottos',  'autoex',}
    },
	['fd'] = {
        ['name'] = 'RX7 FD',
        ['brand'] = 'Mazda',
        ['model'] = 'fd',
        ['price'] = 155000,
        ['category'] = 'tuner',
        ['hash'] = `fd`,
        ['shop'] = {'tuner', 'ottos',  'autoex',}
    },
	['mfc'] = {
        ['name'] = 'RX7 FC',
        ['brand'] = 'Mazda',
        ['model'] = 'mfc',
        ['price'] = 115000,
        ['category'] = 'tuner',
        ['hash'] = `mfc`,
        ['shop'] = {'tuner', 'ottos',  'autoex',}
    },
	['f40'] = {
        ['name'] = 'F40',
        ['brand'] = 'Ferrari',
        ['model'] = 'f40',
        ['price'] = 185000,
        ['category'] = 'tuner',
        ['hash'] = `f40`,
        ['shop'] = {'tuner', 'ottos',  'autoex',}
    },
	['f512tr'] = {
        ['name'] = 'F512',
        ['brand'] = 'Ferrari',
        ['model'] = 'f512tr',
        ['price'] = 205000,
        ['category'] = 'tuner',
        ['hash'] = `f512tr`,
        ['shop'] = {'tuner', 'ottos',  'autoex',}
    },
	['f8hrs'] = {
        ['name'] = 'F8',
        ['brand'] = 'Ferrari',
        ['model'] = 'f8hrs',
        ['price'] = 225000,
        ['category'] = 'tuner',
        ['hash'] = `f8hrs`,
        ['shop'] = {'tuner', 'ottos',  'autoex',}
    },
	['evo9'] = {
        ['name'] = 'Evo 9',
        ['brand'] = 'Mitsubishi',
        ['model'] = 'evo9',
        ['price'] = 135000,
        ['category'] = 'tuner',
        ['hash'] = `evo9`,
        ['shop'] = {'tuner', 'ottos',  'autoex',}
    },
	['er34n'] = {
        ['name'] = 'ER34',
        ['brand'] = 'Nissan',
        ['model'] = 'er34n',
        ['price'] = 142000,
        ['category'] = 'tuner',
        ['hash'] = `er34n`,
        ['shop'] = {'tuner', 'ottos',  'autoex',}
    },
	['ek9'] = {
        ['name'] = 'EK9',
        ['brand'] = 'Honda',
        ['model'] = 'ek9',
        ['price'] = 110000,
        ['category'] = 'tuner',
        ['hash'] = `ek9`,
        ['shop'] = {'tuner', 'ottos',  'autoex',}
    },
	['ecr33'] = {
        ['name'] = 'GTS25 Skyline',
        ['brand'] = 'Nissan',
        ['model'] = 'ecr33',
        ['price'] = 137000,
        ['category'] = 'tuner',
        ['hash'] = `ecr33`,
        ['shop'] = {'tuner', 'ottos',  'autoex',}
    },
	['honcrx91'] = {
        ['name'] = '1991 CRX',
        ['brand'] = 'Honda',
        ['model'] = 'honcrx91',
        ['price'] = 117000,
        ['category'] = 'tuner',
        ['hash'] = `honcrx91`,
        ['shop'] = {'tuner', 'ottos',  'autoex',}
    },
	['cresta90'] = {
        ['name'] = '1990 Cresta',
        ['brand'] = 'Toyota',
        ['model'] = 'cresta90',
        ['price'] = 142000,
        ['category'] = 'tuner',
        ['hash'] = `cresta90`,
        ['shop'] = {'tuner', 'ottos',  'autoex',}
    },
	['cresta81'] = {
        ['name'] = '1981 Cresta',
        ['brand'] = 'Toyota',
        ['model'] = 'cresta81',
        ['price'] = 137000,
        ['category'] = 'tuner',
        ['hash'] = `cresta81`,
        ['shop'] = {'tuner', 'ottos',  'autoex',}
    },
	['cp9a'] = {
        ['name'] = 'Evo 6',
        ['brand'] = 'Mitsubishi',
        ['model'] = 'cp9a',
        ['price'] = 142000,
        ['category'] = 'tuner',
        ['hash'] = `cp9a`,
        ['shop'] = {'tuner', 'ottos',  'autoex',}
    },
	['count5'] = {
        ['name'] = 'Countach',
        ['brand'] = 'Lamborghini',
        ['model'] = 'count5',
        ['price'] = 185000,
        ['category'] = 'tuner',
        ['hash'] = `count5`,
        ['shop'] = {'tuner', 'ottos',  'autoex',}
    },
	['chaser90'] = {
        ['name'] = '1990 Chaser',
        ['brand'] = 'Toyota',
        ['model'] = 'chaser90',
        ['price'] = 132000,
        ['category'] = 'tuner',
        ['hash'] = `chaser90`,
        ['shop'] = {'tuner', 'ottos',  'autoex',}
    },
	['celsiorucf30'] = {
        ['name'] = '2003 Celsior',
        ['brand'] = 'Toyota',
        ['model'] = 'celsiorucf30',
        ['price'] = 120000,
        ['category'] = 'tuner',
        ['hash'] = `celsiorucf30`,
        ['shop'] = {'tuner', 'ottos',  'autoex',}
    },
	['celsiorucf21'] = {
        ['name'] = '1994 Celsior',
        ['brand'] = 'Toyota',
        ['model'] = 'celsiorucf21',
        ['price'] = 120000,
        ['category'] = 'tuner',
        ['hash'] = `celsiorucf21`,
        ['shop'] = {'tuner', 'ottos',  'autoex',}
    },
	['celica'] = {
        ['name'] = 'Celica',
        ['brand'] = 'Toyota',
        ['model'] = 'celica',
        ['price'] = 120000,
        ['category'] = 'tuner',
        ['hash'] = `celica`,
        ['shop'] = {'tuner', 'ottos',  'autoex',}
    },
	['c33s13'] = {
        ['name'] = 'C33 S13',
        ['brand'] = 'Nissan',
        ['model'] = 'c33s13',
        ['price'] = 120000,
        ['category'] = 'tuner',
        ['hash'] = `c33s13`,
        ['shop'] = {'tuner', 'ottos',  'autoex',}
    },
	['bnr34'] = {
        ['name'] = 'R34 Skyline',
        ['brand'] = 'Nissan',
        ['model'] = 'bnr34',
        ['price'] = 120000,
        ['category'] = 'tuner',
        ['hash'] = `bnr34`,
        ['shop'] = {'tuner', 'ottos',  'autoex',}
    },
	['amuses2k'] = {
        ['name'] = 'Amuse S2000',
        ['brand'] = 'Honda',
        ['model'] = 'amuses2k',
        ['price'] = 120000,
        ['category'] = 'tuner',
        ['hash'] = `amuses2k`,
        ['shop'] = {'tuner', 'ottos',  'autoex',}
    },
	['amgbs'] = {
        ['name'] = 'GT AMG',
        ['brand'] = 'Mercedes',
        ['model'] = 'amgbs',
        ['price'] = 120000,
        ['category'] = 'tuner',
        ['hash'] = `amgbs`,
        ['shop'] = {'tuner', 'ottos',  'autoex',}
    },
	['altezza'] = {
        ['name'] = 'Altezza',
        ['brand'] = 'Toyota',
        ['model'] = 'altezza',
        ['price'] = 120000,
        ['category'] = 'tuner',
        ['hash'] = `altezza`,
        ['shop'] = {'tuner', 'ottos',  'autoex',}
    },
	['ae86'] = {
        ['name'] = 'AE86',
        ['brand'] = 'Toyota',
        ['model'] = 'ae86',
        ['price'] = 120000,
        ['category'] = 'tuner',
        ['hash'] = `ae86`,
        ['shop'] = {'tuner', 'ottos',  'autoex',}
    },
	['jza70'] = {
        ['name'] = 'JZA70 Supra',
        ['brand'] = 'Toyota',
        ['model'] = 'jza70',
        ['price'] = 120000,
        ['category'] = 'tuner',
        ['hash'] = `jza70`,
        ['shop'] = {'tuner', 'ottos',  'autoex',}
    },
	['911r'] = {
        ['name'] = '911 GT3',
        ['brand'] = 'Porsche',
        ['model'] = '911r',
        ['price'] = 120000,
        ['category'] = 'tuner',
        ['hash'] = `911r`,
        ['shop'] = {'tuner', 'ottos',  'autoex',}
    },
	['850'] = {
        ['name'] = '850 CSi',
        ['brand'] = 'BMW',
        ['model'] = '850',
        ['price'] = 120000,
        ['category'] = 'tuner',
        ['hash'] = `850`,
        ['shop'] = {'tuner', 'ottos',  'autoex',}
    },
	['458it'] = {
        ['name'] = '458',
        ['brand'] = 'Ferrari',
        ['model'] = '458it',
        ['price'] = 120000,
        ['category'] = 'tuner',
        ['hash'] = `458it`,
        ['shop'] = {'tuner', 'ottos',  'autoex',}
    },
	['350zstardast'] = {
        ['name'] = 'Stardast 350z',
        ['brand'] = 'Nissan',
        ['model'] = '350zstardast',
        ['price'] = 120000,
        ['category'] = 'tuner',
        ['hash'] = `350zstardast`,
        ['shop'] = {'tuner', 'ottos',  'autoex',}
    },
	['190e'] = {
        ['name'] = '190e',
        ['brand'] = 'Mercedes',
        ['model'] = '190e',
        ['price'] = 120000,
        ['category'] = 'tuner',
        ['hash'] = `190e`,
        ['shop'] = {'tuner', 'ottos',  'autoex',}
    },
	['nis180'] = {
        ['name'] = '180sx',
        ['brand'] = 'Nissan',
        ['model'] = 'nis180',
        ['price'] = 120000,
        ['category'] = 'tuner',
        ['hash'] = `nis180`,
        ['shop'] = {'tuner', 'ottos',  'autoex',}
    },
	['daisx'] = {
        ['name'] = 'Discount Tire 180sx',
        ['brand'] = 'Nissan',
        ['model'] = 'daisx',
        ['price'] = 120000,
        ['category'] = 'tuner',
        ['hash'] = `daisx`,
        ['shop'] = {'tuner', 'ottos',  'autoex',}
    },
	['350z'] = {
        ['name'] = '350z',
        ['brand'] = 'Nissan',
        ['model'] = '350z',
        ['price'] = 120000,
        ['category'] = 'tuner',
        ['hash'] = `350z`,
        ['shop'] = {'tuner', 'ottos',  'autoex',}
    },
	['720s'] = {
        ['name'] = '720s',
        ['brand'] = 'Mclaren',
        ['model'] = '720s',
        ['price'] = 120000,
        ['category'] = 'tuner',
        ['hash'] = `720s`,
        ['shop'] = {'tuner', 'ottos',  'autoex',}
    },
	['2000gtr'] = {
        ['name'] = '2000 GTR',
        ['brand'] = 'Nissan',
        ['model'] = '2000gtr',
        ['price'] = 120000,
        ['category'] = 'tuner',
        ['hash'] = `2000gtr`,
        ['shop'] = {'tuner', 'ottos',  'autoex',}
    },
	['a31'] = {
        ['name'] = 'A31',
        ['brand'] = 'Cefiro',
        ['model'] = 'a31',
        ['price'] = 120000,
        ['category'] = 'tuner',
        ['hash'] = `a31`,
        ['shop'] = {'tuner', 'ottos',  'autoex',}
    },
	['ae86t'] = {
        ['name'] = 'AE86 Time Attack',
        ['brand'] = 'Toyota',
        ['model'] = 'ae86t',
        ['price'] = 120000,
        ['category'] = 'tuner',
        ['hash'] = `ae86t`,
        ['shop'] = {'tuner', 'ottos',  'autoex',}
    },
	['a80tbk'] = {
        ['name'] = 'MK4 Supra Midnight',
        ['brand'] = 'Toyota',
        ['model'] = 'a80tbk',
        ['price'] = 120000,
        ['category'] = 'tuner',
        ['hash'] = `a80tbk`,
        ['shop'] = {'tuner', 'ottos',  'autoex',}
    },
	['amis300'] = {
        ['name'] = 'IS 300',
        ['brand'] = 'Lexus',
        ['model'] = 'amis300',
        ['price'] = 120000,
        ['category'] = 'tuner',
        ['hash'] = `amis300`,
        ['shop'] = {'tuner', 'ottos',  'autoex',}
    },
	['c63w204'] = {
        ['name'] = 'C63',
        ['brand'] = 'Mercedes',
        ['model'] = 'c63w204',
        ['price'] = 120000,
        ['category'] = 'tuner',
        ['hash'] = `c63w204`,
        ['shop'] = {'tuner', 'ottos',  'autoex',}
    },
	['evo3'] = {
        ['name'] = 'Evo 3',
        ['brand'] = 'Mitsubishi',
        ['model'] = 'evo3',
        ['price'] = 120000,
        ['category'] = 'tuner',
        ['hash'] = `evo3`,
        ['shop'] = {'tuner', 'ottos',  'autoex',}
    },
	['nis13'] = {
        ['name'] = 'S13',
        ['brand'] = 'Nissan',
        ['model'] = 'nis13',
        ['price'] = 120000,
        ['category'] = 'tuner',
        ['hash'] = `nis13`,
        ['shop'] = {'tuner', 'ottos',  'autoex',},
		['tier'] = 'A+',
		
    },
	['nisr32'] = {
        ['name'] = 'R32 Skyline',
        ['brand'] = 'Nissan',
        ['model'] = 'nisr32',
        ['price'] = 120000,
        ['category'] = 'tuner',
        ['hash'] = `nisr32`,
        ['shop'] = {'tuner', 'ottos',  'autoex',}
    },
	['nisr33'] = {
        ['name'] = 'R33 Skyline',
        ['brand'] = 'Nissan',
        ['model'] = 'nisr33',
        ['price'] = 120000,
        ['category'] = 'tuner',
        ['hash'] = `nisr33`,
        ['shop'] = {'tuner', 'ottos',  'autoex',}
    },
	['r33hr'] = {
        ['name'] = 'HR R33 Skyline',
        ['brand'] = 'Nissan',
        ['model'] = 'r33hr',
        ['price'] = 120000,
        ['category'] = 'tuner',
        ['hash'] = `r33hr`,
        ['shop'] = {'tuner', 'ottos',  'autoex',}
    },
	['skyr34'] = {
        ['name'] = 'R34 Skyline 2',
        ['brand'] = 'Nissan',
        ['model'] = 'skyr34',
        ['price'] = 120000,
        ['category'] = 'tuner',
        ['hash'] = `skyr34`,
        ['shop'] = {'tuner', 'ottos',  'autoex',}
    },
	['r34mn'] = {
        ['name'] = 'R34 Skyline Midnight',
        ['brand'] = 'Nissan',
        ['model'] = 'r34mn',
        ['price'] = 120000,
        ['category'] = 'tuner',
        ['hash'] = `r34mn`,
        ['shop'] = {'tuner', 'ottos',  'autoex',}
    },
	['nissil80'] = {
        ['name'] = 'Sleighty',
        ['brand'] = 'Nissan',
        ['model'] = 'nissil80',
        ['price'] = 120000,
        ['category'] = 'tuner',
        ['hash'] = `nissil80`,
        ['shop'] = {'tuner', 'ottos',  'autoex',}
    },
	['benzsl63'] = {
        ['name'] = 'SL63',
        ['brand'] = 'Mercedes',
        ['model'] = 'benzsl63',
        ['price'] = 120000,
        ['category'] = 'tuner',
        ['hash'] = `benzsl63`,
        ['shop'] = {'tuner', 'ottos',  'autoex',}
    },
	['toysupmk4'] = {
        ['name'] = 'MK4 Supra',
        ['brand'] = 'Toyota',
        ['model'] = 'toysupmk4',
        ['price'] = 120000,
        ['category'] = 'tuner',
        ['hash'] = `toysupmk4`,
        ['shop'] = {'tuner', 'ottos',  'autoex',}
    },
	['z32'] = {
        ['name'] = 'Z32',
        ['brand'] = 'Nissan',
        ['model'] = 'z32',
        ['price'] = 120000,
        ['category'] = 'tuner',
        ['hash'] = `z32`,
        ['shop'] = {'tuner', 'ottos',  'autoex',}
    },
	['nscw'] = {
        ['name'] = 'R34 Skyline CW',
        ['brand'] = 'Nissan',
        ['model'] = 'nscw',
        ['price'] = 120000,
        ['category'] = 'tuner',
        ['hash'] = `nscw`,
        ['shop'] = {'tuner', 'ottos',  'autoex',}
    },
	['evovaris'] = {
        ['name'] = 'Varis EVO',
        ['brand'] = 'Mitsubishi',
        ['model'] = 'evovaris',
        ['price'] = 120000,
        ['category'] = 'tuner',
        ['hash'] = `evovaris`,
        ['shop'] = {'tuner', 'ottos',  'autoex',}
    },
	['m4hr'] = {
        ['name'] = 'M4 HR',
        ['brand'] = 'BMW',
        ['model'] = 'm4hr',
        ['price'] = 120000,
        ['category'] = 'tuner',
        ['hash'] = `m4hr`,
        ['shop'] = {'tuner', 'ottos',  'autoex',}
    },
	['vettehachi'] = {
        ['name'] = 'Hachi Corvette',
        ['brand'] = 'Chevy',
        ['model'] = 'vettehachi',
        ['price'] = 120000,
        ['category'] = 'tuner',
        ['hash'] = `vettehachi`,
        ['shop'] = {'tuner', 'ottos',  'autoex',}
    },
	['r34rdsmonster'] = {
        ['name'] = 'R34 RDS Monster',
        ['brand'] = 'Nissan',
        ['model'] = 'r34rdsmonster',
        ['price'] = 120000,
        ['category'] = 'tuner',
        ['hash'] = `r34rdsmonster`,
        ['shop'] = {'tuner', 'ottos',  'autoex',}
    },
	['na6'] = {
        ['name'] = 'Miata',
        ['brand'] = 'Mazda',
        ['model'] = 'na6',
        ['price'] = 120000,
        ['category'] = 'tuner',
        ['hash'] = `na6`,
        ['shop'] = {'tuner', 'ottos',  'autoex',}
    },
	['mr2sw20'] = {
        ['name'] = 'MR2',
        ['brand'] = 'Toyota',
        ['model'] = 'mr2sw20',
        ['price'] = 120000,
        ['category'] = 'tuner',
        ['hash'] = `mr2sw20`,
        ['shop'] = {'tuner', 'ottos',  'autoex',}
    },
	['mk2100'] = {
        ['name'] = 'JZX100 MK2',
        ['brand'] = 'Toyota',
        ['model'] = 'mk2100',
        ['price'] = 120000,
        ['category'] = 'tuner',
        ['hash'] = `mk2100`,
        ['shop'] = {'tuner', 'ottos',  'autoex',}
    },
	['mk2100'] = {
        ['name'] = 'JZX100 MK2',
        ['brand'] = 'Toyota',
        ['model'] = 'mk2100',
        ['price'] = 120000,
        ['category'] = 'tuner',
        ['hash'] = `mk2100`,
        ['shop'] = {'tuner', 'ottos',  'autoex',}
    },
	['mazfd'] = {
        ['name'] = 'Tuner FD RX7',
        ['brand'] = 'Mazda',
        ['model'] = 'mazfd',
        ['price'] = 120000,
        ['category'] = 'tuner',
        ['hash'] = `mazfd`,
        ['shop'] = {'tuner', 'ottos',  'autoex',}
    },
	['lfahachi'] = {
        ['name'] = 'Hachi LFA',
        ['brand'] = 'Lexus',
        ['model'] = 'lfahachi',
        ['price'] = 120000,
        ['category'] = 'tuner',
        ['hash'] = `lfahachi`,
        ['shop'] = {'tuner', 'ottos',  'autoex',}
    },
	['levin86'] = {
        ['name'] = 'Levin 86',
        ['brand'] = 'Levin',
        ['model'] = 'levin86',
        ['price'] = 120000,
        ['category'] = 'tuner',
        ['hash'] = `levin86`,
        ['shop'] = {'tuner', 'ottos',  'autoex',}
    },
	['lc500'] = {
        ['name'] = 'LC500',
        ['brand'] = 'Lexus',
        ['model'] = 'lc500',
        ['price'] = 120000,
        ['category'] = 'tuner',
        ['hash'] = `lc500`,
        ['shop'] = {'tuner', 'ottos',  'autoex',}
    },
	['lc500'] = {
        ['name'] = 'LC500',
        ['brand'] = 'Lexus',
        ['model'] = 'lc500',
        ['price'] = 120000,
        ['category'] = 'tuner',
        ['hash'] = `lc500`,
        ['shop'] = {'tuner', 'ottos',  'autoex',}
    },
	['jzs161'] = {
        ['name'] = 'GS340',
        ['brand'] = 'Lexus',
        ['model'] = 'jzs161',
        ['price'] = 120000,
        ['category'] = 'tuner',
        ['hash'] = `jzs161`,
        ['shop'] = {'tuner', 'ottos',  'autoex',}
    },
	['jzs147'] = {
        ['name'] = 'Aristo',
        ['brand'] = 'Toyota',
        ['model'] = 'jzs147',
        ['price'] = 120000,
        ['category'] = 'tuner',
        ['hash'] = `jzs147`,
        ['shop'] = {'tuner', 'ottos',  'autoex',}
    },
	['dc2'] = {
        ['name'] = 'Integra',
        ['brand'] = 'Honda',
        ['model'] = 'dc2',
        ['price'] = 120000,
        ['category'] = 'tuner',
        ['hash'] = `dc2`,
        ['shop'] = {'tuner', 'ottos',  'autoex',}
    },
	['sim22'] = {
        ['name'] = '22b',
        ['brand'] = 'Subaru',
        ['model'] = 'sim22',
        ['price'] = 120000,
        ['category'] = 'tuner',
        ['hash'] = `sim22`,
        ['shop'] = {'tuner', 'ottos',  'autoex',}
    },
	['928gtsmn'] = {
        ['name'] = '928 Midnight',
        ['brand'] = 'Porsche',
        ['model'] = '928gtsmn',
        ['price'] = 120000,
        ['category'] = 'tuner',
        ['hash'] = `928gtsmn`,
        ['shop'] = {'tuner', 'ottos',  'autoex',}
    },
	]]--












